/* ============================================================
   DezoMax — Telekanallar / Телеканалы
   ------------------------------------------------------------
   Jonli HLS oqimlar. Manba: iptv-org ochiq katalogi (ommaviy efir).
   Barchasi https va CORS bilan tekshirilgan.

   Yangi kanal qo'shish: shu ro'yxatga obyekt qo'shing.
     id       - takrorlanmas kod
     name     - kanal nomi
     category - pastdagi CHANNEL_CATS ro'yxatidan
     url      - .m3u8 havolasi (albatta https bo'lsin, aks holda
                brauzer HTTPS saytda uni bloklaydi)
     colors   - kartochka gradienti
   ============================================================ */

const CHANNEL_CATS = [
  { id: 'general', uz: 'Umumiy', ru: 'Общие' },
  { id: 'news', uz: 'Yangiliklar', ru: 'Новости' },
  { id: 'movies', uz: 'Kino', ru: 'Кино' },
  { id: 'entertainment', uz: 'Ko‘ngilochar', ru: 'Развлекательные' },
  { id: 'music', uz: 'Musiqa', ru: 'Музыка' },
  { id: 'sports', uz: 'Sport', ru: 'Спорт' },
  { id: 'kids', uz: 'Bolalar', ru: 'Детские' },
  { id: 'family', uz: 'Oilaviy', ru: 'Семейные' },
  { id: 'documentary', uz: 'Hujjatli', ru: 'Документальные' }
];

const CHANNELS = [
  { id: 'Ozbekiston', name: "O'zbekiston", category: 'general',
    url: 'https://stream8.cinerama.uz/1001/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Yoshlar', name: "Yoshlar", category: 'general',
    url: 'https://stream8.cinerama.uz/1002/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Sport', name: "Sport", category: 'sports',
    url: 'https://stream8.cinerama.uz/1004/tracks-v1a1/mono.m3u8',
    colors: ['#2a6b3a', '#08160c'] },
  { id: 'FTV', name: "FTV", category: 'music',
    url: 'https://stream8.cinerama.uz/1018/playlist.m3u8',
    colors: ['#2a5a5a', '#081414'] },
  { id: 'Milliy', name: "Milliy", category: 'general',
    url: 'https://stream8.cinerama.uz/1014/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Ozbekiston24', name: "O'zbekiston 24", category: 'news',
    url: 'https://stream8.cinerama.uz/1011/tracks-v1a1/playlist.m3u8',
    colors: ['#5a2a2a', '#140808'] },
  { id: 'SevimliTV', name: "Sevimli TV", category: 'family',
    url: 'https://stream8.cinerama.uz/1017/tracks-v1a1/playlist.m3u8',
    colors: ['#4a5a2a', '#101408'] },
  { id: 'ZorTV', name: "Zo'r TV", category: 'entertainment',
    url: 'https://stream8.cinerama.uz/1016/tracks-v1a1/mono.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'Toshkent', name: "Toshkent", category: 'general',
    url: 'https://stream8.cinerama.uz/1003/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Madaniyatvamarifat', name: "Madaniyat va ma'rifat", category: 'general',
    url: 'https://stream8.cinerama.uz/1005/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Bolajon', name: "Bolajon", category: 'kids',
    url: 'https://stream8.cinerama.uz/1007/playlist.m3u8',
    colors: ['#6b5a1e', '#161206'] },
  { id: 'Kinoteatr', name: "Kinoteatr", category: 'movies',
    url: 'https://stream8.cinerama.uz/1009/tracks-v1a1/playlist.m3u8',
    colors: ['#4a2a6b', '#100818'] },
  { id: 'Aqlvoy', name: "Aqlvoy", category: 'kids',
    url: 'https://stream8.cinerama.uz/1205/tracks-v1a1/mono.m3u8',
    colors: ['#6b5a1e', '#161206'] },
  { id: 'BIZCinema', name: "BIZ Cinema", category: 'movies',
    url: 'https://fl.biztv.media/cinema_720_EMfSyXgoRdiIHgldXTZICucKTIeCKO/index.m3u8',
    colors: ['#4a2a6b', '#100818'] },
  { id: 'BIZMusic', name: "BIZ Music", category: 'music',
    url: 'https://fl.biztv.media/music_720_QAKpGmVUjaPApCNjpsgBxrdqNihAkl/index.m3u8',
    colors: ['#2a5a5a', '#081414'] },
  { id: 'BIZTV', name: "BIZ TV", category: 'entertainment',
    url: 'https://fl.biztv.media/biz_tv_720_uni8jhub4h8fub4idejswh8dh3j94finbu4nidj39inwsj92in3d/index.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'CheksizTV', name: "Cheksiz TV", category: 'entertainment',
    url: 'https://fl.biztv.media/cheksiz_tv_480_unif7hujidth7f4du83jrhuid3k94j8hfj8d93eubych8eju93n4ubt/tracks-v1a1/mono.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'DasturxonTV', name: "Dasturxon TV", category: 'general',
    url: 'https://stream8.cinerama.uz/1206/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Dunyoboylab', name: "Dunyo bo'ylab", category: 'general',
    url: 'https://stream8.cinerama.uz/1006/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'FargonaMTRK', name: "Farg'ona MTRK", category: 'general',
    url: 'https://stream8.cinerama.uz/1458/tracks-v1a1/mono.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Mahalla', name: "Mahalla", category: 'general',
    url: 'https://stream8.cinerama.uz/1013/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'MakonTV', name: "Makon TV", category: 'entertainment',
    url: 'https://stream8.cinerama.uz/1497/tracks-v1a1/mono.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'MuzTVUzbekistan', name: "Muz TV Uzbekistan", category: 'music',
    url: 'https://stream8.cinerama.uz/1063/tracks-v1a1/mono.m3u8',
    colors: ['#2a5a5a', '#081414'] },
  { id: 'MY5', name: "MY5", category: 'entertainment',
    url: 'https://stream8.cinerama.uz/1217/tracks-v1a1/playlist.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'Navo', name: "Navo", category: 'general',
    url: 'https://stream8.cinerama.uz/1008/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'NavoiyMTRK', name: "Navoiy MTRK", category: 'general',
    url: 'https://stream8.cinerama.uz/1460/tracks-v1a1/mono.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'NurafshonTV', name: "Nurafshon TV", category: 'general',
    url: 'https://stream8.cinerama.uz/1220/tracks-v1a1/mono.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'OzbekistonTarixi', name: "O'zbekiston Tarixi", category: 'documentary',
    url: 'https://stream8.cinerama.uz/1209/tracks-v1a1/playlist.m3u8',
    colors: ['#3a4a5a', '#0c1014'] },
  { id: 'Qaraqalpaqstan', name: "Qaraqalpaqstan", category: 'general',
    url: 'https://stream8.cinerama.uz/1467/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'RenessansTV', name: "Renessans TV", category: 'general',
    url: 'https://stream8.cinerama.uz/1221/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'TaraqqiyotTV', name: "Taraqqiyot TV", category: 'general',
    url: 'https://stream8.cinerama.uz/1204/tracks-v1a1/mono.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'UzReportTV', name: "UzReport TV", category: 'news',
    url: 'https://stream8.cinerama.uz/1015/tracks-v1a1/playlist.m3u8',
    colors: ['#5a2a2a', '#140808'] }
];
