/* ============================================================
   DezoMax — Telekanallar / Телеканалы
   ------------------------------------------------------------
   Jonli HLS oqimlar. Manba: iptv-org ochiq katalogi (ommaviy efir).
   Har bir oqim https va CORS jihatidan tekshirilgan.

   Yangi kanal qo'shish:
     id       - takrorlanmas kod
     name     - kanal nomi
     country  - 'uz' | 'ru'  (ro'yxatda guruhlash uchun)
     category - 'general' | 'news' | 'movies' | 'entertainment' |
                'music' | 'sports' | 'kids' | 'family' | 'documentary'
     logo     - images/tv/ ichidagi rasm yoki null
     url      - .m3u8 havolasi. ALBATTA https bo'lsin — sayt HTTPS da
                turgani uchun brauzer http:// oqimlarni bloklaydi.
                Server CORS ruxsatini ham berishi shart.
     colors   - logotip bo'lmaganda ishlatiladigan gradient
   ============================================================ */

const CHANNEL_COUNTRIES = [
  { id: 'uz', uz: 'O\u2018zbekiston kanallari', ru: '\u0423\u0437\u0431\u0435\u043a\u0441\u043a\u0438\u0435 \u043a\u0430\u043d\u0430\u043b\u044b' },
  { id: 'ru', uz: 'Rossiya kanallari',           ru: '\u0420\u043e\u0441\u0441\u0438\u0439\u0441\u043a\u0438\u0435 \u043a\u0430\u043d\u0430\u043b\u044b' }
];

const CHANNELS = [
  { id: 'Ozbekiston', name: "O'zbekiston", country: 'uz', category: 'general',
    logo: 'images/tv/Ozbekiston.png',
    url: 'https://stream8.cinerama.uz/1001/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Yoshlar', name: "Yoshlar", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1002/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Sport', name: "Sport", country: 'uz', category: 'sports',
    logo: 'images/tv/Sport.jpg',
    url: 'https://stream8.cinerama.uz/1004/tracks-v1a1/mono.m3u8',
    colors: ['#2a6b3a', '#08160c'] },
  { id: 'FTV', name: "FTV", country: 'uz', category: 'music',
    logo: null,
    url: 'https://stream8.cinerama.uz/1018/playlist.m3u8',
    colors: ['#2a5a5a', '#081414'] },
  { id: 'Milliy', name: "Milliy", country: 'uz', category: 'general',
    logo: 'images/tv/Milliy.jpg',
    url: 'https://stream8.cinerama.uz/1014/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Ozbekiston24', name: "O'zbekiston 24", country: 'uz', category: 'news',
    logo: null,
    url: 'https://stream8.cinerama.uz/1011/tracks-v1a1/playlist.m3u8',
    colors: ['#5a2a2a', '#140808'] },
  { id: 'SevimliTV', name: "Sevimli TV", country: 'uz', category: 'family',
    logo: null,
    url: 'https://stream8.cinerama.uz/1017/tracks-v1a1/playlist.m3u8',
    colors: ['#4a5a2a', '#101408'] },
  { id: 'ZorTV', name: "Zo'r TV", country: 'uz', category: 'entertainment',
    logo: 'images/tv/ZorTV.jpg',
    url: 'https://stream8.cinerama.uz/1016/tracks-v1a1/mono.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'Toshkent', name: "Toshkent", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1003/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Bolajon', name: "Bolajon", country: 'uz', category: 'kids',
    logo: null,
    url: 'https://stream8.cinerama.uz/1007/playlist.m3u8',
    colors: ['#6b5a1e', '#161206'] },
  { id: 'Kinoteatr', name: "Kinoteatr", country: 'uz', category: 'movies',
    logo: null,
    url: 'https://stream8.cinerama.uz/1009/tracks-v1a1/playlist.m3u8',
    colors: ['#4a2a6b', '#100818'] },
  { id: 'Aqlvoy', name: "Aqlvoy", country: 'uz', category: 'kids',
    logo: null,
    url: 'https://stream8.cinerama.uz/1205/tracks-v1a1/mono.m3u8',
    colors: ['#6b5a1e', '#161206'] },
  { id: 'BIZCinema', name: "BIZ Cinema", country: 'uz', category: 'movies',
    logo: 'images/tv/BIZCinema.png',
    url: 'https://fl.biztv.media/cinema_720_EMfSyXgoRdiIHgldXTZICucKTIeCKO/index.m3u8',
    colors: ['#4a2a6b', '#100818'] },
  { id: 'BIZMusic', name: "BIZ Music", country: 'uz', category: 'music',
    logo: 'images/tv/BIZMusic.jpg',
    url: 'https://fl.biztv.media/music_720_QAKpGmVUjaPApCNjpsgBxrdqNihAkl/index.m3u8',
    colors: ['#2a5a5a', '#081414'] },
  { id: 'BIZTV', name: "BIZ TV", country: 'uz', category: 'entertainment',
    logo: 'images/tv/BIZTV.png',
    url: 'https://fl.biztv.media/biz_tv_720_uni8jhub4h8fub4idejswh8dh3j94finbu4nidj39inwsj92in3d/index.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'CheksizTV', name: "Cheksiz TV", country: 'uz', category: 'entertainment',
    logo: null,
    url: 'https://fl.biztv.media/cheksiz_tv_480_unif7hujidth7f4du83jrhuid3k94j8hfj8d93eubych8eju93n4ubt/tracks-v1a1/mono.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'DasturxonTV', name: "Dasturxon TV", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1206/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Dunyoboylab', name: "Dunyo bo'ylab", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1006/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'FargonaMTRK', name: "Farg'ona MTRK", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1458/tracks-v1a1/mono.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Madaniyatvamarifat', name: "Madaniyat va ma'rifat", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1005/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Mahalla', name: "Mahalla", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1013/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'MakonTV', name: "Makon TV", country: 'uz', category: 'entertainment',
    logo: null,
    url: 'https://stream8.cinerama.uz/1497/tracks-v1a1/mono.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'MuzTVUzbekistan', name: "Muz TV Uzbekistan", country: 'uz', category: 'music',
    logo: 'images/tv/MuzTVUzbekistan.jpg',
    url: 'https://stream8.cinerama.uz/1063/tracks-v1a1/mono.m3u8',
    colors: ['#2a5a5a', '#081414'] },
  { id: 'MY5', name: "MY5", country: 'uz', category: 'entertainment',
    logo: null,
    url: 'https://stream8.cinerama.uz/1217/tracks-v1a1/playlist.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'Navo', name: "Navo", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1008/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'NavoiyMTRK', name: "Navoiy MTRK", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1460/tracks-v1a1/mono.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'NurafshonTV', name: "Nurafshon TV", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1220/tracks-v1a1/mono.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'OzbekistonTarixi', name: "O'zbekiston Tarixi", country: 'uz', category: 'documentary',
    logo: null,
    url: 'https://stream8.cinerama.uz/1209/tracks-v1a1/playlist.m3u8',
    colors: ['#3a4a5a', '#0c1014'] },
  { id: 'Qaraqalpaqstan', name: "Qaraqalpaqstan", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1467/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'RenessansTV', name: "Renessans TV", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1221/tracks-v1a1/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'TaraqqiyotTV', name: "Taraqqiyot TV", country: 'uz', category: 'general',
    logo: null,
    url: 'https://stream8.cinerama.uz/1204/tracks-v1a1/mono.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'UzReportTV', name: "UzReport TV", country: 'uz', category: 'news',
    logo: null,
    url: 'https://stream8.cinerama.uz/1015/tracks-v1a1/playlist.m3u8',
    colors: ['#5a2a2a', '#140808'] },
  { id: 'ChannelOneRU', name: "Первый канал", country: 'ru', category: 'general',
    logo: 'images/tv/ChannelOneRU.png',
    url: 'https://streaming.thestream.cyou/live/210.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'RENTVInternationalRU', name: "РЕН ТВ", country: 'ru', category: 'general',
    logo: null,
    url: 'https://fs.uplink.kz/ren/mono.m3u8?token=onlinetv',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'NTVMirRU', name: "НТВ Мир", country: 'ru', category: 'general',
    logo: 'images/tv/NTVMirRU.png',
    url: 'https://fs.uplink.kz/ntv_mir/mono.m3u8?token=onlinetv',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'ZvezdaRU', name: "Звезда", country: 'ru', category: 'general',
    logo: null,
    url: 'https://tvchannelstream1.tvzvezda.ru/cdn/tvzvezda/playlist.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'TNT4RU', name: "ТНТ4", country: 'ru', category: 'entertainment',
    logo: 'images/tv/TNT4RU.png',
    url: 'https://zabava-htlive.cdn.ngenix.net/hls/CH_TNT4/variant.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'CarouselRU', name: "Карусель", country: 'ru', category: 'kids',
    logo: 'images/tv/CarouselRU.png',
    url: 'https://stream.smotrim.ru/hls2/karusel/playlist_3.m3u8',
    colors: ['#6b5a1e', '#161206'] },
  { id: 'MultRU', name: "Мульт", country: 'ru', category: 'kids',
    logo: null,
    url: 'https://fs.uplink.kz/mult/mono.m3u8?token=onlinetv',
    colors: ['#6b5a1e', '#161206'] },
  { id: 'DomkinoRU', name: "Дом кино", country: 'ru', category: 'movies',
    logo: 'images/tv/DomkinoRU.png',
    url: 'https://fs.uplink.kz/dom_kino/mono.m3u8?token=onlinetv',
    colors: ['#4a2a6b', '#100818'] },
  { id: 'CinemaRU', name: "Кинотеатр Cinema", country: 'ru', category: 'movies',
    logo: null,
    url: 'https://stream8.cinerama.uz/1227/tracks-v1a1/mono.m3u8',
    colors: ['#4a2a6b', '#100818'] },
  { id: 'MatchPlanetaRU', name: "Матч! Планета", country: 'ru', category: 'sports',
    logo: 'images/tv/MatchPlanetaRU.png',
    url: 'https://fs.uplink.kz/match_planeta/mono.m3u8?token=onlinetv',
    colors: ['#2a6b3a', '#08160c'] },
  { id: 'MuzTVRU', name: "Муз-ТВ", country: 'ru', category: 'music',
    logo: 'images/tv/MuzTVRU.png',
    url: 'https://stream8.cinerama.uz/1200/tracks-v1a1/mono.m3u8',
    colors: ['#2a5a5a', '#081414'] },
  { id: '360RU', name: "360°", country: 'ru', category: 'general',
    logo: null,
    url: 'https://cdn-evacoder-tv.facecast.io/evacoder_hls_hi/CkxfR1xNUAJwTgtXTBZTAJli/index.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: '360NewsRU', name: "360° News", country: 'ru', category: 'news',
    logo: null,
    url: 'https://live-vgtrksmotrim.cdnvideo.ru/vgtrksmotrim/smotrim-live-03-srt.smil/playlist.m3u8',
    colors: ['#5a2a2a', '#140808'] },
  { id: '365daysTVRU', name: "365 дней ТВ", country: 'ru', category: 'documentary',
    logo: 'images/tv/365daysTVRU.png',
    url: 'https://stream8.cinerama.uz/1242/tracks-v1a1/mono.m3u8',
    colors: ['#3a4a5a', '#0c1014'] },
  { id: 'ArsenalRU', name: "Арсенал", country: 'ru', category: 'documentary',
    logo: null,
    url: 'https://stream8.cinerama.uz/1414/tracks-v1a1/mono.m3u8',
    colors: ['#3a4a5a', '#0c1014'] },
  { id: 'BigPlanetRU', name: "Big Planet", country: 'ru', category: 'general',
    logo: null,
    url: 'https://fs.uplink.kz/big_planet/mono.m3u8?token=onlinetv',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'BRIDGEClassicRU', name: "BRIDGE Classic", country: 'ru', category: 'music',
    logo: 'images/tv/BRIDGEClassicRU.png',
    url: 'https://fs.uplink.kz/bridge_classic/mono.m3u8?token=onlinetv',
    colors: ['#2a5a5a', '#081414'] },
  { id: 'CarouselInternationalRU', name: "Карусель International", country: 'ru', category: 'kids',
    logo: 'images/tv/CarouselInternationalRU.png',
    url: 'https://fs.uplink.kz/karusel/mono.m3u8?token=onlinetv',
    colors: ['#6b5a1e', '#161206'] },
  { id: 'Channel5InternationalRU', name: "Пятый канал", country: 'ru', category: 'general',
    logo: 'images/tv/Channel5InternationalRU.png',
    url: 'https://cdn4.skygo.mn/live/disk1/Channel_5/HLSv3-FTA/Channel_5.m3u8',
    colors: ['#2a4a6b', '#0a1220'] },
  { id: 'Channel8RU', name: "Восьмой канал", country: 'ru', category: 'entertainment',
    logo: null,
    url: 'https://v4.proofix.ru/8tv-russia/index.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'CheRU', name: "Чё!", country: 'ru', category: 'entertainment',
    logo: 'images/tv/CheRU.png',
    url: 'https://zabava-htlive.cdn.ngenix.net/hls/CH_PERETZ/variant.m3u8',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'CityEdenTeleNovellaRU', name: "Теленовелла", country: 'ru', category: 'movies',
    logo: null,
    url: 'https://cityeden.catcast.tv/content/46209/index.m3u8',
    colors: ['#4a2a6b', '#100818'] },
  { id: 'DaVinciRU', name: "Da Vinci", country: 'ru', category: 'documentary',
    logo: null,
    url: 'https://stream8.cinerama.uz/1231/tracks-v1a1/mono.m3u8',
    colors: ['#3a4a5a', '#0c1014'] },
  { id: 'DetvoraPlusRU', name: "Detvora+", country: 'ru', category: 'kids',
    logo: 'images/tv/DetvoraPlusRU.png',
    url: 'https://cdn.rostelekom-tv.xyz/live/WAYU4PTJ_VVz4wAQ.m3u8',
    colors: ['#6b5a1e', '#161206'] },
  { id: 'DoctorRU', name: "Доктор", country: 'ru', category: 'documentary',
    logo: null,
    url: 'https://stream8.cinerama.uz/1409/tracks-v1a1/mono.m3u8',
    colors: ['#3a4a5a', '#0c1014'] },
  { id: 'DomkinoPremiumRU', name: "Дом кино Премиум", country: 'ru', category: 'movies',
    logo: null,
    url: 'https://fs.uplink.kz/dom_kino_premium/mono.m3u8?token=onlinetv',
    colors: ['#4a2a6b', '#100818'] },
  { id: 'DomashniyRU', name: "Домашний", country: 'ru', category: 'entertainment',
    logo: 'images/tv/DomashniyRU.png',
    url: 'https://fs.uplink.kz/domashniy/mono.m3u8?token=onlinetv',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'DoramaRU', name: "Дорама", country: 'ru', category: 'movies',
    logo: null,
    url: 'https://stream8.cinerama.uz/1273/tracks-v1a1/mono.m3u8',
    colors: ['#4a2a6b', '#100818'] },
  { id: 'KHLRU', name: "КХЛ", country: 'ru', category: 'sports',
    logo: 'images/tv/KHLRU.png',
    url: 'https://fs.uplink.kz/telekanal_khl/mono.m3u8?token=onlinetv',
    colors: ['#2a6b3a', '#08160c'] },
  { id: 'KHLPrimeRU', name: "КХЛ Prime", country: 'ru', category: 'sports',
    logo: 'images/tv/KHLPrimeRU.png',
    url: 'https://fs.uplink.kz/khl_prime/mono.m3u8?token=onlinetv',
    colors: ['#2a6b3a', '#08160c'] },
  { id: 'MatchUltraRU', name: "Матч! Ультра", country: 'ru', category: 'sports',
    logo: 'images/tv/MatchUltraRU.jpg',
    url: 'https://fs.uplink.kz/match/mono.m3u8?token=onlinetv',
    colors: ['#2a6b3a', '#08160c'] },
  { id: 'MultilandiaRU', name: "Мультиландия", country: 'ru', category: 'kids',
    logo: null,
    url: 'https://stream8.cinerama.uz/1440/tracks-v1a1/mono.m3u8',
    colors: ['#6b5a1e', '#161206'] },
  { id: 'TNT4InternationalRU', name: "ТНТ4 International", country: 'ru', category: 'entertainment',
    logo: 'images/tv/TNT4InternationalRU.png',
    url: 'https://fs.uplink.kz/tnt4/mono.m3u8?token=onlinetv',
    colors: ['#6b2a4a', '#160810'] },
  { id: 'vijuHistoryRU', name: "viju History", country: 'ru', category: 'documentary',
    logo: 'images/tv/vijuHistoryRU.png',
    url: 'https://fs.uplink.kz/viju_history/mono.m3u8?token=onlinetv',
    colors: ['#3a4a5a', '#0c1014'] }
];
