/* DezoMax Shorts — ruxsat berilgan kanallarning qisqa videolari (tools/fetch-yt-meta.js, admin → «Kanallar» yozadi).
   YouTube pleyeri orqali ko'rsatiladi (shorts.html). id — YouTube video ID, t — nomi, s — soniya. */
var SHORTS = /*SHORTS*/[
{"id":"_8Jmr-eLlJg","t":"Eng kuchli bolg‘a","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":84},
{"id":"oICBqgDwTMo","t":"Premyeraga kim bilan borasiz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":13},
{"id":"MkTzGiY6NUc","t":"Lockdown - a knight?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":38},
{"id":"o9mmUnvoiHc","t":"Qasoskorlar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":52},
{"id":"GNCJ92i5qQ4","t":"Barcha o‘lgan va tirik qolgan deseptikonlar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":59},
{"id":"pZ-WGMEPCww","t":"Drift Eng Mohir Qilichboz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":42},
{"id":"qdOe8Yoj47w","t":"O‘lgan va Tirik qolgan avtobotlar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":28},
{"id":"MKDx_Xt8ySw","t":"Wrekkerlar - kimlar?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":32},
{"id":"uOK_JJMqYJs","t":"Deyneris tirikmi?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":32},
{"id":"c8Ni7ID8DVg","t":"SHOCKWAVE - eng xavfli deseptikon","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":55},
{"id":"gevFIKHIp4c","t":"Exx o‘sha yillar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":12},
{"id":"Cru1EfOsZgU","t":"Starscream - eng aqilli maniplyator","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":63},
{"id":"UHPRJWeuWcw","t":"LOCKDOWN - eng yaxshi yovuz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":57},
{"id":"rHqR1HpVSmI","t":"Qasoskorlar 5 Yangiliklar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":34},
{"id":"KmHV1owLt64","t":"Drift eng qo‘rqmas avtobot","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":34},
{"id":"a1QHIFL8b7o","t":"Bumblebee buni bilgan!","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":22},
{"id":"fvWetebpv8Y","t":"Chaqmoq Makvin Kim Bilan Uchrashardi?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":53},
{"id":"j5PlUfoCga4","t":"Call of Dutyning filmi suratga olinadi","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":31},
{"id":"yZH4XUporZw","t":"WheelJack-eng omadsiz avtobot!","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":32},
{"id":"bCa_axmIjF8","t":"Cheksizlik toshlarini kim birinchi yiqqan?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":24},
{"id":"sIc2o8ACn_k","t":"Devastator - eng qiyin robot","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":62},
{"id":"_JGMMJhigMY","t":"Optimus praym","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":32},
{"id":"XfbarUSrqL0","t":"Wednesday 2- sezon tahlili | o‘zbek tilida","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":11},
{"id":"otCn6rQGuWg","t":"Wednesday 2- sezon tahlili | o‘zbek tilida","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":6},
{"id":"nR71aF-NWEA","t":"Who do you choose","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":22},
{"id":"5g0BL1sEXQ4","t":"Yangi Avtobotlar - Qadimiy Jangchilar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":34},
{"id":"ZgXaMlxuxeE","t":"Crosshairs - Qotil Avtobot","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":27},
{"id":"N87k48LjKz0","t":"Jekson Bo‘ron Qanday Mashina?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":21},
{"id":"0B0dBWTB1vg","t":"Chaqmoq Makvin Qanday Mashina?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":33},
{"id":"XYsETzdmu_0","t":"Optimus Praym Qanday Mashinalarga aylangan?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":41},
{"id":"yCbYixjhsno","t":"Bambilbining dushmani kim?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":28},
{"id":"A6SWqMHWKLI","t":"Drift - eng qo‘rqmas avtobot","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":34},
{"id":"DcFaoywZVpo","t":"Mashxur Aktyorlar nechi yoshda","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":48},
{"id":"5S4JZo-R1_Y","t":"Momaqaldiroqlar Jahon Premyerasi","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":37},
{"id":"4m2tfLZzmS0","t":"Why Can’t Autobots Fly?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":45},
{"id":"NuxIdRQTB1U","t":"Eng qimmat Transformer qaysi?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":55},
{"id":"T9x4lFIlc4o","t":"Nima uchun Kogmanning tanasi kichkina?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":34},
{"id":"nkcE80Wj1Kc","t":"Megatron buni hech qachon aytmagan","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":29},
{"id":"WRdgQX3w6DY","t":"Nima uchun Drift Bambilbini yomon ko‘radi?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":49},
{"id":"0WxerdbQiio","t":"Oskar 2025 haqida","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":34},
{"id":"YhPzK82am1M","t":"Nega Bunday","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":37},
{"id":"fOm_NWTeAmE","t":"Nega Iron Hide","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":40},
{"id":"_pZ4Z_XIUKo","t":"Bambilbi real hayotda ham bormi","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":39},
{"id":"21JYag74weU","t":"Sentinal Soxta Praymmi?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":28},
{"id":"2NVS_1qWJ0M","t":"Optimusning Yashirin Qobilyati","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":36},
{"id":"yAMozmyJUXM","t":"Nega Transformerlar Sport Carlarga aylanadi?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":28},
{"id":"HTv7yw5TZZE","t":"Kimni tanlaysiz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":21},
{"id":"SuDomQyiMqM","t":"Tay lung haqida 5 ta fakt","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":60},
{"id":"Xqat7wK5cWM","t":"Dedpul va rosamaxa jahon premyerasi","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":38},
{"id":"1ko-U0Psyog","t":"Qaysi Darsga Kirasiz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":33},
{"id":"bwja_8l_stU","t":"Eski Qasoskorlar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":25},
{"id":"rpBWMM3KauE","t":"Marvel","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":56},
{"id":"Vebq8cDomlg","t":"Tanos rostan ham haq edi","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":34},
{"id":"rd9jf7GSMGY","t":"Qaysi birini tanlaysiz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":19},
{"id":"YOqNDy6l0k0","t":"Afsonaviy uchlik","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":20},
{"id":"Vr1uNHrW8U4","t":"Top 5 new avengers","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":23},
{"id":"lLxaRfh0DqA","t":"Biz sevgan multfilmlar qanday yakun topgan","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":29},
{"id":"vfIbkjkmGO8","t":"Qaysi darsga kirasiz?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":36},
{"id":"JT5u3YArZ9c","t":"Afsonaviy uchlik dc","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":20},
{"id":"JPy9EmtOmjU","t":"Afsonaviy uchlik","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":20},
{"id":"O86BextRr7o","t":"Temir odamni yenga oladigan qahramonlar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":30},
{"id":"40TyzYkh6IA","t":"Biz sevgan multfilmlar qanday yakun topgan","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":29},
{"id":"5Z33tMkf9-4","t":"Biz sevgan multfilmlar qanday yakun topgan","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":25},
{"id":"lO_KRAGsVU8","t":"Selestialni o‘ldira oladigan qahramonlar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":30},
{"id":"u9EmoYxuxaY","t":"Marvel vs dc","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":42},
{"id":"XrGweICm4II","t":"Marvel dance","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":33},
{"id":"VvEfP0LR0A0","t":"Qaysi birini tanlaysiz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":20},
{"id":"X17Dd8JD9_s","t":"Mortal kombat 1 | kimni tanlaysiz? | what your favorit","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":19},
{"id":"N5ZNZVhrKco","t":"Temir odamlar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":51},
{"id":"B51SAeY9eqU","t":"Qaysi sinf kuchli","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":41},
{"id":"XDQjS1rlg3E","t":"Yulduzlar lordi!","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":27},
{"id":"egfrCpFW7rs","t":"Kuch toshi haqida","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":51},
{"id":"zDs0En1lTbs","t":"Marvel mix","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":19},
{"id":"XGxGWWbqeys","t":"Kimni tanlaysiz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":25},
{"id":"ZCKl07B1Zkk","t":"Temir Odam","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":10},
{"id":"kfIzbFASSFw","t":"Adolat Ligasini O‘zbek sanatkorla oynaganda","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":21},
{"id":"JxGt5SraS9U","t":"Qaysi darsga kirasiz?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":24},
{"id":"uPbornim35Q","t":"Eng kuchli Transformerlar","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":23},
{"id":"GxSvakNBjVI","t":"Supermen vs ikaris","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":38},
{"id":"lApByPifabU","t":"Qaysi Birini Tanlaysiz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":19},
{"id":"vpXKpy1irbQ","t":"Kimni muxlisisiz?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":19},
{"id":"JAIoufn2QqU","t":"Wanda vs klea. Kim kuchli?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":43},
{"id":"ClIM0DZUykQ","t":"Qaysi birini tanlaysiz","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":16},
{"id":"Wr7f8hbr-4E","t":"Temir odam vs betmen","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":43},
{"id":"adf0Q97miWc","t":"Altron va Vijin suhbati","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":61},
{"id":"q2HAPbU0rOQ","t":"Tor supermenga qarshi #","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":43},
{"id":"bkOhlV3Nv7U","t":"Wanda","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":35},
{"id":"39drgMZZ_hY","t":"Temir Odam","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":14},
{"id":"Okz7Cp2_UyM","t":"Kang Torga Qarshi. Kim Kuchli 4","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":26},
{"id":"-qwuGUbt7Es","t":"Wednesday Marvelda?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":23},
{"id":"KIiUWaYmJfI","t":"Wednesday","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":10},
{"id":"Sn3j4MVv1XE","t":"Buni bilarmidingiz?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":36},
{"id":"IUDrnejFxQI","t":"Odin Borson kim?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":42},
{"id":"uToJzahnBcY","t":"Buni bilarmidingiz?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":16},
{"id":"mlnNCINnAok","t":"Kim kuchli?","ch":"farzidguy","n":"FarZidGuy","u":"https://www.youtube.com/@FarZidGuy","s":29}
]/*ENDSHORTS*/;
