/* tools/fetch-marvel.js yaratadi — Wikidata (CC0) ma'lumotlari. Qo'lda o'zgartirmang. */
var MARVEL_INFO = {
 "32": {
  "wd": "Q192724",
  "en": "Iron Man",
  "date": "2008-04-30",
  "runtime": 126,
  "director": [
   "Jon Favreau"
  ],
  "cast": [
   "Robert Downey Jr.",
   "Terrence Howard",
   "Jeff Bridges",
   "Gwyneth Paltrow",
   "Shaun Toub",
   "Faran Tahir",
   "Leslie Bibb",
   "Clark Gregg",
   "Bill Smitrovich",
   "Paul Bettany",
   "Jon Favreau",
   "Samuel L. Jackson"
  ],
  "budget": 140000000,
  "gross": 585366247
 },
 "33": {
  "wd": "Q182218",
  "en": "The Avengers",
  "date": "2012-04-25",
  "runtime": 142,
  "director": [
   "Joss Whedon"
  ],
  "cast": [
   "Jillian Morgese",
   "Robert Downey Jr.",
   "Chris Evans",
   "Mark Ruffalo",
   "Chris Hemsworth",
   "Scarlett Johansson",
   "Jeremy Renner",
   "Tom Hiddleston",
   "Clark Gregg",
   "Cobie Smulders",
   "Stellan Skarsgård",
   "Samuel L. Jackson"
  ],
  "budget": 220000000,
  "gross": 1518812988,
  "yt": "eOrNdBpGMv8",
  "ytCh": "Marvel Entertainment"
 },
 "34": {
  "wd": "Q5887360",
  "en": "Guardians of the Galaxy",
  "date": "2014-07-31",
  "runtime": 121,
  "director": [
   "James Gunn"
  ],
  "cast": [
   "Chris Pratt",
   "Dave Bautista",
   "Zoe Saldaña",
   "Michael Rooker",
   "Lee Pace",
   "Ophelia Lovibond",
   "Karen Gillan",
   "Djimon Hounsou",
   "Glenn Close",
   "Josh Brolin",
   "Benicio del Toro",
   "John C. Reilly"
  ],
  "budget": 170000000,
  "gross": 772776600,
  "yt": "d96cjJhvlMA",
  "ytCh": "Marvel Entertainment"
 },
 "35": {
  "wd": "Q1765358",
  "en": "Captain America: The Winter Soldier",
  "date": "2014-03-26",
  "runtime": 136,
  "director": [
   "Anthony Russo",
   "Joe Russo"
  ],
  "cast": [
   "Robert Redford",
   "Chris Evans",
   "Scarlett Johansson",
   "Sebastian Stan",
   "Anthony Mackie",
   "Cobie Smulders",
   "Frank Grillo",
   "Georges St-Pierre",
   "Samuel L. Jackson",
   "Aaron Taylor-Johnson",
   "Alan Dale",
   "Bernard White"
  ],
  "budget": 170000000,
  "gross": 714421503,
  "yt": "7SlILk2WMTI",
  "ytCh": "Marvel Entertainment"
 },
 "36": {
  "wd": "Q18406872",
  "en": "Doctor Strange",
  "date": "2016-10-20",
  "runtime": 115,
  "director": [
   "Scott Derrickson"
  ],
  "cast": [
   "Benedict Cumberbatch",
   "Chiwetel Ejiofor",
   "Rachel McAdams",
   "Michael Stuhlbarg",
   "Mads Mikkelsen",
   "Tilda Swinton",
   "Amy Landecker",
   "Scott Adkins",
   "Benedict Wong",
   "Benjamin Bratt",
   "Zara Phythian",
   "Alaa Safi"
  ],
  "budget": 165000000,
  "gross": 677718395,
  "yt": "HSzx-zryEgM",
  "ytCh": "Marvel Entertainment"
 },
 "37": {
  "wd": "Q22665878",
  "en": "Thor: Ragnarok",
  "date": "2017-10-25",
  "runtime": 130,
  "director": [
   "Taika Waititi"
  ],
  "cast": [
   "Chris Hemsworth",
   "Tom Hiddleston",
   "Mark Ruffalo",
   "Cate Blanchett",
   "Tessa Thompson",
   "Jeff Goldblum",
   "Karl Urban",
   "Idris Elba",
   "Anthony Hopkins",
   "Sam Neill",
   "Benedict Cumberbatch",
   "Rachel House"
  ],
  "budget": 180000000,
  "gross": 853977126,
  "yt": "BynD1PEVAB4",
  "ytCh": "Marvel Entertainment"
 },
 "38": {
  "wd": "Q23780734",
  "en": "Black Panther",
  "date": "2018-02-14",
  "runtime": 134,
  "director": [
   "Ryan Coogler"
  ],
  "cast": [
   "Chadwick Boseman",
   "Michael B. Jordan",
   "Lupita Nyong'o",
   "Danai Gurira",
   "Winston Duke",
   "Andy Serkis",
   "Forest Whitaker",
   "Florence Kasumba",
   "Daniel Kaluuya",
   "Letitia Wright",
   "Angela Bassett",
   "Sterling K. Brown"
  ],
  "budget": 200000000,
  "gross": 1347597973,
  "yt": "xjDjIWPwcPU",
  "ytCh": "Marvel Entertainment"
 },
 "39": {
  "wd": "Q23780914",
  "en": "Avengers: Infinity War",
  "date": "2018-04-25",
  "runtime": 149,
  "director": [
   "Anthony Russo",
   "Joe Russo"
  ],
  "cast": [
   "Chris Hemsworth",
   "Mark Ruffalo",
   "Chris Evans",
   "Josh Brolin",
   "Tom Hiddleston",
   "Robert Downey Jr.",
   "Samuel L. Jackson",
   "Chris Pratt",
   "Benedict Cumberbatch",
   "Paul Bettany",
   "Elizabeth Olsen",
   "Sebastian Stan"
  ],
  "budget": 400000000,
  "gross": 2048359754,
  "yt": "6ZfuNTqbHE8",
  "ytCh": "Marvel Entertainment"
 },
 "40": {
  "wd": "Q23781155",
  "en": "Avengers: Endgame",
  "date": "2019-04-22",
  "runtime": 181,
  "director": [
   "Anthony Russo",
   "Joe Russo"
  ],
  "cast": [
   "Chris Hemsworth",
   "Mark Ruffalo",
   "Chris Evans",
   "Josh Brolin",
   "Tom Hiddleston",
   "Robert Downey Jr.",
   "Samuel L. Jackson",
   "Chris Pratt",
   "Elizabeth Olsen",
   "Evangeline Lilly",
   "Benedict Cumberbatch",
   "Jeremy Renner"
  ],
  "budget": 356000000,
  "gross": 2797501328,
  "yt": "TcMBFSGVi1c",
  "ytCh": "Marvel Entertainment"
 },
 "41": {
  "wd": "Q68934496",
  "en": "Spider-Man: No Way Home",
  "date": "2021-12-15",
  "runtime": 148,
  "director": [
   "Jon Watts"
  ],
  "cast": [
   "Tom Holland",
   "Zendaya",
   "Marisa Tomei",
   "Jacob Batalon",
   "Tony Revolori",
   "Benedict Cumberbatch",
   "Alfred Molina",
   "Jamie Foxx",
   "Jon Favreau",
   "J. B. Smoove",
   "Benedict Wong",
   "Angourie Rice"
  ],
  "budget": 200000000,
  "gross": 1921847111,
  "yt": "ZYzbalQ6Lg8",
  "ytCh": "Marvel Entertainment"
 },
 "42": {
  "wd": "Q19347291",
  "en": "Deadpool",
  "date": "2016-02-10",
  "runtime": 108,
  "director": [
   "Tim Miller"
  ],
  "cast": [
   "Ryan Reynolds",
   "Morena Baccarin",
   "Ed Skrein",
   "T. J. Miller",
   "Gina Carano",
   "Brianna Hildebrand",
   "Andre Tricoteux",
   "Leslie Uggams",
   "Jed Rees",
   "Karan Soni",
   "Taylor Hickson",
   "Randal Reeder"
  ],
  "budget": 58000000,
  "gross": 782836791,
  "yt": "ONHBaC-pfsk",
  "ytCh": "20th Century Studios"
 },
 "43": {
  "wd": "Q29588607",
  "en": "Spider-Man: Into the Spider-Verse",
  "date": "2018-12-13",
  "runtime": 116,
  "director": [
   "Peter Ramsey",
   "Rodney Rothman",
   "Bob Persichetti"
  ],
  "cast": [],
  "budget": 90000000,
  "gross": 363800000,
  "yt": "XfJ1PFzE8DU",
  "ytCh": "Marvel Entertainment"
 },
 "122": {
  "wd": "Q466611",
  "en": "The Incredible Hulk",
  "date": "2008-06-13",
  "runtime": 112,
  "director": [
   "Louis Leterrier"
  ],
  "cast": [
   "Edward Norton",
   "Liv Tyler",
   "Tim Roth",
   "William Hurt",
   "Tim Blake Nelson",
   "Ty Burrell",
   "Peter Mensah",
   "Robert Downey Jr.",
   "Lou Ferrigno",
   "Stan Lee",
   "Christina Cabot",
   "Débora Nascimento"
  ],
  "budget": 150000000,
  "gross": 263427551
 },
 "123": {
  "wd": "Q205028",
  "en": "Iron Man 2",
  "date": "2010-04-29",
  "runtime": 125,
  "director": [
   "Jon Favreau"
  ],
  "cast": [
   "Robert Downey Jr.",
   "Gwyneth Paltrow",
   "Don Cheadle",
   "Scarlett Johansson",
   "Sam Rockwell",
   "Mickey Rourke",
   "Samuel L. Jackson",
   "Clark Gregg",
   "John Slattery",
   "Garry Shandling",
   "Kate Mara",
   "Leslie Bibb"
  ],
  "budget": 200000000,
  "gross": 623933331
 },
 "124": {
  "wd": "Q217020",
  "en": "Thor",
  "date": "2011-04-27",
  "runtime": 114,
  "director": [
   "Kenneth Branagh"
  ],
  "cast": [
   "Kat Dennings",
   "Chris Hemsworth",
   "Natalie Portman",
   "Tom Hiddleston",
   "Stellan Skarsgård",
   "Colm Feore",
   "Ray Stevenson",
   "Idris Elba",
   "Rene Russo",
   "Anthony Hopkins",
   "Clark Gregg",
   "Jaimie Alexander"
  ],
  "budget": 150000000,
  "gross": 449326618,
  "yt": "JOddp-nlNvQ",
  "ytCh": "Marvel Entertainment"
 },
 "125": {
  "wd": "Q275120",
  "en": "Captain America: The First Avenger",
  "date": "2011-07-22",
  "runtime": 124,
  "director": [
   "Joe Johnston"
  ],
  "cast": [
   "Tommy Lee Jones",
   "Hayley Atwell",
   "Stanley Tucci",
   "Chris Evans",
   "Hugo Weaving",
   "Sebastian Stan",
   "Dominic Cooper",
   "Neal McDonough",
   "Derek Luke",
   "Toby Jones",
   "Samuel L. Jackson",
   "Richard Armitage"
  ],
  "budget": 140000000,
  "gross": 370569774,
  "yt": "JerVrbLldXw",
  "ytCh": "Marvel Entertainment"
 },
 "126": {
  "wd": "Q209538",
  "en": "Iron Man 3",
  "date": "2013-04-24",
  "runtime": 130,
  "director": [
   "Shane Black"
  ],
  "cast": [
   "Robert Downey Jr.",
   "Gwyneth Paltrow",
   "Don Cheadle",
   "Guy Pearce",
   "Rebecca Hall",
   "Jon Favreau",
   "Ben Kingsley",
   "James Badge Dale",
   "Stephanie Szostak",
   "William Sadler",
   "Dale Dickey",
   "Ty Simpkins"
  ],
  "budget": 200000000,
  "gross": 1214811252,
  "yt": "Ke1Y3P9D0Bc",
  "ytCh": "Marvel UK"
 },
 "127": {
  "wd": "Q1201853",
  "en": "Thor: The Dark World",
  "date": "2013-10-31",
  "runtime": 112,
  "director": [
   "Alan Taylor"
  ],
  "cast": [
   "Kat Dennings",
   "Chris Hemsworth",
   "Natalie Portman",
   "Tom Hiddleston",
   "Stellan Skarsgård",
   "Idris Elba",
   "Christopher Eccleston",
   "Adewale Akinnuoye-Agbaje",
   "Ray Stevenson",
   "Zachary Levi",
   "Tadanobu Asano",
   "Jaimie Alexander"
  ],
  "budget": 170000000,
  "gross": 644783140,
  "yt": "npvJ9FTgZbM",
  "ytCh": "Marvel Entertainment"
 },
 "128": {
  "wd": "Q14171368",
  "en": "Avengers: Age of Ultron",
  "date": "2015-04-22",
  "runtime": 141,
  "director": [
   "Joss Whedon"
  ],
  "cast": [
   "Robert Downey Jr.",
   "Chris Evans",
   "Mark Ruffalo",
   "Samuel L. Jackson",
   "Aaron Taylor-Johnson",
   "Scarlett Johansson",
   "James Spader",
   "Hayley Atwell",
   "Chris Hemsworth",
   "Jeremy Renner",
   "Don Cheadle",
   "Elizabeth Olsen"
  ],
  "budget": 250000000,
  "gross": 1402805868,
  "yt": "tmeOjFno6Do",
  "ytCh": "Marvel Entertainment"
 },
 "129": {
  "wd": "Q5901134",
  "en": "Ant-Man",
  "date": "2015-07-14",
  "runtime": 117,
  "director": [
   "Peyton Reed"
  ],
  "cast": [
   "Paul Rudd",
   "Evangeline Lilly",
   "Corey Stoll",
   "Bobby Cannavale",
   "Michael Peña",
   "Judy Greer",
   "T.I.",
   "David Dastmalchian",
   "Wood Harris",
   "Michael Douglas",
   "Anthony Mackie",
   "Abby Ryder Fortson"
  ],
  "budget": 130000000,
  "gross": 519311965,
  "yt": "pWdKf3MneyI",
  "ytCh": "Marvel Entertainment"
 },
 "130": {
  "wd": "Q18407657",
  "en": "Captain America: Civil War",
  "date": "2016-04-27",
  "runtime": 147,
  "director": [
   "Anthony Russo",
   "Joe Russo"
  ],
  "cast": [
   "Robert Downey Jr.",
   "Scarlett Johansson",
   "Sebastian Stan",
   "Anthony Mackie",
   "Jeremy Renner",
   "Don Cheadle",
   "Elizabeth Olsen",
   "Paul Rudd",
   "Emily VanCamp",
   "Frank Grillo",
   "William Hurt",
   "Chadwick Boseman"
  ],
  "budget": 250000000,
  "gross": 1153296293,
  "yt": "dKrVegVI0Us",
  "ytCh": "Marvel Entertainment"
 },
 "131": {
  "wd": "Q20001199",
  "en": "Guardians of the Galaxy Vol. 2",
  "date": "2017-04-10",
  "runtime": 136,
  "director": [
   "James Gunn"
  ],
  "cast": [
   "Chris Pratt",
   "Zoe Saldaña",
   "Dave Bautista",
   "Michael Rooker",
   "Karen Gillan",
   "Sean Gunn",
   "Pom Klementieff",
   "Steve Agee",
   "Kurt Russell",
   "Elizabeth Debicki",
   "Chris Sullivan",
   "Tommy Flanagan"
  ],
  "budget": 200000000,
  "gross": 863756051,
  "yt": "wUn05hdkhjM",
  "ytCh": "Marvel Entertainment"
 },
 "132": {
  "wd": "Q23010088",
  "en": "Spider-Man: Homecoming",
  "date": "2017-06-28",
  "runtime": 133,
  "director": [
   "Jon Watts"
  ],
  "cast": [
   "Tom Holland",
   "Marisa Tomei",
   "Zendaya",
   "Tony Revolori",
   "Laura Harrier",
   "Robert Downey Jr.",
   "Michael Keaton",
   "Donald Glover",
   "Martin Starr",
   "Abraham Attah",
   "Selenis Leyva",
   "Logan Marshall-Green"
  ],
  "budget": 175000000,
  "gross": 880166924,
  "yt": "39udgGPyYMg",
  "ytCh": "Marvel Entertainment"
 },
 "133": {
  "wd": "Q22957393",
  "en": "Ant-Man and the Wasp",
  "date": "2018-07-04",
  "runtime": 118,
  "director": [
   "Peyton Reed"
  ],
  "cast": [
   "Paul Rudd",
   "Evangeline Lilly",
   "Michael Peña",
   "Michael Douglas",
   "Bobby Cannavale",
   "T.I.",
   "Judy Greer",
   "David Dastmalchian",
   "Laurence Fishburne",
   "Hannah John-Kamen",
   "Randall Park",
   "Walton Goggins"
  ],
  "budget": 162000000,
  "gross": 622674139,
  "yt": "8_rTIAOohas",
  "ytCh": "Marvel Entertainment"
 },
 "134": {
  "wd": "Q23781129",
  "en": "Captain Marvel",
  "date": "2019-03-06",
  "runtime": 124,
  "director": [
   "Ryan Fleck",
   "Anna Boden"
  ],
  "cast": [
   "Brie Larson",
   "Samuel L. Jackson",
   "Jude Law",
   "Gemma Chan",
   "Clark Gregg",
   "Lee Pace",
   "Ben Mendelsohn",
   "Djimon Hounsou",
   "Mckenna Grace",
   "Lashana Lynch",
   "Algenis Perez Soto",
   "Rune Temte"
  ],
  "budget": 152000000,
  "gross": 1128462972,
  "yt": "Z1BCujX3pw8",
  "ytCh": "Marvel Entertainment"
 },
 "135": {
  "wd": "Q27985819",
  "en": "Spider-Man: Far From Home",
  "date": "2019-06-28",
  "runtime": 129,
  "director": [
   "Jon Watts"
  ],
  "cast": [
   "Tom Holland",
   "Samuel L. Jackson",
   "Jake Gyllenhaal",
   "Marisa Tomei",
   "Jon Favreau",
   "Zendaya",
   "Jacob Batalon",
   "Tony Revolori",
   "Angourie Rice",
   "Remy Hii",
   "Martin Starr",
   "J. B. Smoove"
  ],
  "budget": 160000000,
  "gross": 1131927996,
  "yt": "LFoz8ZJWmPs",
  "ytCh": "Marvel Entertainment"
 },
 "136": {
  "wd": "Q23894626",
  "en": "Black Widow",
  "date": "2021-07-07",
  "runtime": 133,
  "director": [
   "Cate Shortland"
  ],
  "cast": [
   "Scarlett Johansson",
   "David Harbour",
   "Rachel Weisz",
   "O. T. Fagbenle",
   "Florence Pugh",
   "Ray Winstone",
   "William Hurt",
   "Ahmed Bakare",
   "Joakim Skarli",
   "Simona Brown-Zivkovska",
   "Olga Kurylenko",
   "Olivier Richters"
  ],
  "budget": 200000000,
  "gross": 379751655,
  "yt": "ybji16u608U",
  "ytCh": "Marvel Entertainment"
 },
 "137": {
  "wd": "Q65768589",
  "en": "Shang-Chi and the Legend of the Ten Rings",
  "date": "2021-09-01",
  "runtime": 132,
  "director": [
   "Destin Daniel Cretton"
  ],
  "cast": [
   "Simu Liu",
   "Tony Leung",
   "Awkwafina",
   "Fala Chen",
   "Florian Munteanu",
   "Ronny Chieng",
   "Ben Kingsley",
   "Benedict Wong",
   "Michelle Yeoh",
   "Dallas Liu",
   "Yuen Wah",
   "Jodi Long"
  ],
  "budget": 150000000,
  "gross": 432243292,
  "yt": "8YjFbMbfXaQ",
  "ytCh": "Marvel Entertainment"
 },
 "138": {
  "wd": "Q23894629",
  "en": "Eternals",
  "date": "2021-11-03",
  "runtime": 156,
  "director": [
   "Chloé Zhao"
  ],
  "cast": [
   "Angelina Jolie",
   "Richard Madden",
   "Salma Hayek",
   "Kumail Nanjiani",
   "Lauren Ridloff",
   "Brian Tyree Henry",
   "Ma Dong-seok",
   "Lia McHugh",
   "Gemma Chan",
   "Barry Keoghan",
   "Kit Harington",
   "Haaz Sleiman"
  ],
  "budget": 236200000,
  "gross": 402064899
 },
 "139": {
  "wd": "Q64211112",
  "en": "Doctor Strange in the Multiverse of Madness",
  "date": "2022-05-04",
  "runtime": 126,
  "director": [
   "Sam Raimi"
  ],
  "cast": [
   "Benedict Cumberbatch",
   "Benedict Wong",
   "Chiwetel Ejiofor",
   "Elizabeth Olsen",
   "Rachel McAdams",
   "Xochitl Gomez",
   "Michael Stuhlbarg",
   "Patrick Stewart",
   "Hayley Atwell",
   "Lashana Lynch",
   "Anson Mount",
   "John Krasinski"
  ],
  "budget": 200000000,
  "gross": 955775804,
  "yt": "aWzlQ2N6qqg",
  "ytCh": "Marvel Entertainment"
 },
 "140": {
  "wd": "Q65768604",
  "en": "Thor: Love and Thunder",
  "date": "2022-07-06",
  "runtime": 119,
  "director": [
   "Taika Waititi"
  ],
  "cast": [
   "Chris Hemsworth",
   "Tessa Thompson",
   "Natalie Portman",
   "Taika Waititi",
   "Christian Bale",
   "Chris Pratt",
   "Jaimie Alexander",
   "Pom Klementieff",
   "Matt Damon",
   "Sean Gunn",
   "Luke Hemsworth",
   "Russell Crowe"
  ],
  "budget": 250000000,
  "gross": 760928081,
  "yt": "Go8nTmfrQd8",
  "ytCh": "Marvel Entertainment"
 },
 "141": {
  "wd": "Q54860489",
  "en": "Black Panther: Wakanda Forever",
  "date": "2022-11-09",
  "runtime": 161,
  "director": [
   "Ryan Coogler"
  ],
  "cast": [
   "Letitia Wright",
   "Winston Duke",
   "Angela Bassett",
   "Danai Gurira",
   "Lupita Nyong'o",
   "Florence Kasumba",
   "Dominique Thorne",
   "Daniel Kaluuya",
   "Martin Freeman",
   "Michaela Coel",
   "Tenoch Huerta",
   "Dorothy Steel"
  ],
  "budget": 250000000,
  "gross": 859208836,
  "yt": "_Z3QKkl1WyM",
  "ytCh": "Marvel Entertainment"
 },
 "142": {
  "wd": "Q105359456",
  "en": "Ant-Man and the Wasp: Quantumania",
  "date": "2023-02-15",
  "runtime": 125,
  "director": [
   "Peyton Reed"
  ],
  "cast": [
   "Paul Rudd",
   "Evangeline Lilly",
   "Michael Douglas",
   "Michelle Pfeiffer",
   "Kathryn Newton",
   "Jonathan Majors",
   "Randall Park",
   "Bill Murray",
   "Gregg Turkington",
   "William Jackson Harper",
   "Corey Stoll",
   "Randall Park"
  ],
  "budget": 200000000,
  "gross": 476069301,
  "yt": "ZlNFpri-Y40",
  "ytCh": "Marvel Entertainment"
 },
 "143": {
  "wd": "Q29226331",
  "en": "Guardians of the Galaxy Vol. 3",
  "date": "2023-04-22",
  "runtime": 150,
  "director": [
   "James Gunn"
  ],
  "cast": [
   "Chris Pratt",
   "Zoe Saldaña",
   "Dave Bautista",
   "Karen Gillan",
   "Pom Klementieff",
   "Vin Diesel",
   "Bradley Cooper",
   "Will Poulter",
   "Sylvester Stallone",
   "Sean Gunn",
   "Chuk Iwuji",
   "Michael Rosenbaum"
  ],
  "budget": 250000000,
  "gross": 845555777,
  "yt": "u3V5KDHRQvk",
  "ytCh": "Marvel Entertainment"
 },
 "144": {
  "wd": "Q89474225",
  "en": "The Marvels",
  "date": "2023-11-08",
  "runtime": 105,
  "director": [
   "Nia DaCosta"
  ],
  "cast": [
   "Brie Larson",
   "Teyonah Parris",
   "Iman Vellani",
   "Samuel L. Jackson",
   "Zawe Ashton",
   "Park Seo-joon",
   "Zenobia Shroff",
   "Mohan Kapur",
   "Saagar Shaikh",
   "Lashana Lynch",
   "Randall Park"
  ],
  "budget": 220000000,
  "gross": 206136557,
  "yt": "wS_qbDztgVY",
  "ytCh": "Marvel Entertainment"
 },
 "145": {
  "wd": "Q102180106",
  "en": "Deadpool & Wolverine",
  "date": "2024-07-24",
  "runtime": 128,
  "director": [
   "Shawn Levy"
  ],
  "cast": [
   "Ryan Reynolds",
   "Hugh Jackman",
   "Morena Baccarin",
   "Jennifer Garner",
   "Peggy",
   "Matthew Macfadyen",
   "Emma Corrin",
   "Rob Delaney",
   "Leslie Uggams",
   "Karan Soni",
   "Brianna Hildebrand",
   "Stefan Kapičić"
  ],
  "budget": 200000000,
  "gross": 1338073645,
  "yt": "73_1biulkYk",
  "ytCh": "Marvel Entertainment"
 },
 "146": {
  "wd": "Q112322116",
  "en": "Captain America: Brave New World",
  "date": "2025-02-12",
  "runtime": 118,
  "director": [
   "Julius Onah"
  ],
  "cast": [
   "Anthony Mackie",
   "Danny Ramirez",
   "Tim Blake Nelson",
   "Shira Haas",
   "Carl Lumbly",
   "Harrison Ford",
   "Liv Tyler",
   "Giancarlo Esposito",
   "Xosha Roquemore",
   "Jóhannes Haukur Jóhannesson",
   "Sebastian Stan"
  ],
  "budget": 180000000,
  "gross": null,
  "yt": "1pHDWnXmK7Y",
  "ytCh": "Marvel Entertainment"
 },
 "147": {
  "wd": "Q112322474",
  "en": "Thunderbolts*",
  "date": "2025-05-01",
  "runtime": 126,
  "director": [
   "Jake Schreier"
  ],
  "cast": [
   "Julia Louis-Dreyfus",
   "Olga Kurylenko",
   "Wyatt Russell",
   "David Harbour",
   "Hannah John-Kamen",
   "Sebastian Stan",
   "Florence Pugh",
   "Lewis Pullman",
   "Geraldine Viswanathan",
   "Chris Bauer",
   "Wendell Pierce"
  ],
  "budget": 180000000,
  "gross": null,
  "yt": "hUUszE29jS0",
  "ytCh": "Marvel Entertainment"
 },
 "148": {
  "wd": "Q105105219",
  "en": "The Fantastic Four: First Steps",
  "date": "2025-07-24",
  "runtime": 114,
  "director": [
   "Matt Shakman"
  ],
  "cast": [
   "Pedro Pascal",
   "Vanessa Kirby",
   "Ebon Moss-Bachrach",
   "Joseph Quinn",
   "Ralph Ineson",
   "Julia Garner",
   "Paul Walter Hauser",
   "John Malkovich",
   "Natasha Lyonne",
   "Sarah Niles",
   "Mark Gatiss"
  ],
  "budget": 200000000,
  "gross": null,
  "yt": "pAsmrKyMqaA",
  "ytCh": "Marvel Entertainment"
 },
 "149": {
  "wd": "Q113244935",
  "en": "Spider-Man: Brand New Day",
  "date": "2026-07-29",
  "runtime": 145,
  "director": [
   "Destin Daniel Cretton"
  ],
  "cast": [
   "Tom Holland",
   "Zendaya",
   "Jacob Batalon",
   "Sadie Sink",
   "Liza Colón-Zayas",
   "Jon Bernthal",
   "Mark Ruffalo",
   "Michael Mando",
   "Tramell Tillman",
   "Krondon",
   "Eman Esfandi",
   "Zabryna Guevara"
  ],
  "budget": 225000000,
  "gross": null,
  "yt": "daXaTug8rL4",
  "ytCh": "Marvel Entertainment"
 },
 "150": {
  "yt": "irVNGjRFZGk",
  "ytCh": "Marvel Entertainment"
 }
};
/* Aktyor suratlari — Wikimedia Commons (erkin litsenziya) */
var MARVEL_PHOTOS = {
 "Robert Downey Jr.": "https://commons.wikimedia.org/wiki/Special:FilePath/Robert_Downey_Jr_2014_Comic_Con_(cropped).jpg?width=160",
 "Gwyneth Paltrow": "https://commons.wikimedia.org/wiki/Special:FilePath/Gwyneth_Paltrow_avp_Iron_Man_3_Paris.jpg?width=160",
 "Jeff Bridges": "https://commons.wikimedia.org/wiki/Special:FilePath/Jeff_Bridges_by_Gage_Skidmore_3.jpg?width=160",
 "Terrence Howard": "https://commons.wikimedia.org/wiki/Special:FilePath/Terrence_Howard_-_Monte-Carlo.jpg?width=160",
 "Chris Evans": "https://commons.wikimedia.org/wiki/Special:FilePath/Chris_Evans_Red_2024.jpg?width=160",
 "Scarlett Johansson": "https://commons.wikimedia.org/wiki/Special:FilePath/Scarlett_Johansson-8588.jpg?width=160",
 "Mark Ruffalo": "https://commons.wikimedia.org/wiki/Special:FilePath/Mark_Ruffalo_(36201774756)_(cropped).jpg?width=160",
 "Chris Hemsworth": "https://commons.wikimedia.org/wiki/Special:FilePath/Chris_Hemsworth_-_Crime_101.jpg?width=160",
 "Chris Pratt": "https://commons.wikimedia.org/wiki/Special:FilePath/Chris_Pratt_2018.jpg?width=160",
 "Dave Bautista": "https://commons.wikimedia.org/wiki/Special:FilePath/Dave_Bautista_by_Gage_Skidmore_2.jpg?width=160",
 "Bradley Cooper": "https://commons.wikimedia.org/wiki/Special:FilePath/Bradley_Cooper.jpg?width=160",
 "Vin Diesel": "https://commons.wikimedia.org/wiki/Special:FilePath/Vin_Diesel_2013.jpg?width=160",
 "Sebastian Stan": "https://commons.wikimedia.org/wiki/Special:FilePath/Sebastian_Stan_by_Gage_Skidmore_2_(cropped).jpg?width=160",
 "Robert Redford": "https://commons.wikimedia.org/wiki/Special:FilePath/Tell_Them_Willie_Boy_Is_Here_%E2%80%93_Robert_Redford_photo.jpg?width=160",
 "Benedict Cumberbatch": "https://commons.wikimedia.org/wiki/Special:FilePath/BCumberbatch_Comic-Con_2019.jpg?width=160",
 "Chiwetel Ejiofor": "https://commons.wikimedia.org/wiki/Special:FilePath/Chiwetel_Ejiofor_at_the_2024_Toronto_International_Film_Festival_(cropped).jpg?width=160",
 "Rachel McAdams": "https://commons.wikimedia.org/wiki/Special:FilePath/Rachel_McAdams_-_Walk_of_Fame.jpg?width=160",
 "Tilda Swinton": "https://commons.wikimedia.org/wiki/Special:FilePath/Tilda_Swinton_by_Gage_Skidmore_(cropped).jpg?width=160",
 "Tom Hiddleston": "https://commons.wikimedia.org/wiki/Special:FilePath/Tom_Hiddleston_at_the_2024_Toronto_International_Film_Festival_(cropped).jpg?width=160",
 "Cate Blanchett": "https://commons.wikimedia.org/wiki/Special:FilePath/Cate_Blanchett_Cannes_2018_2_(cropped).jpg?width=160",
 "Chadwick Boseman": "https://commons.wikimedia.org/wiki/Special:FilePath/Chadwick_Boseman_by_Gage_Skidmore_July_2017_(cropped).jpg?width=160",
 "Michael B. Jordan": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_B_Jordan_-_Sinners_(cropped).jpg?width=160",
 "Lupita Nyong'o": "https://commons.wikimedia.org/wiki/Special:FilePath/LupitaNyongo-byPhilipRomano3.jpg?width=160",
 "Danai Gurira": "https://commons.wikimedia.org/wiki/Special:FilePath/Danai_Gurira_2024_(cropped).jpg?width=160",
 "Josh Brolin": "https://commons.wikimedia.org/wiki/Special:FilePath/Josh_Brolin_TIFF_2025_(cropped).jpg?width=160",
 "Tom Holland": "https://commons.wikimedia.org/wiki/Special:FilePath/TomHolland-byPhilipRomano.jpg?width=160",
 "Zendaya": "https://commons.wikimedia.org/wiki/Special:FilePath/Zendaya-byPhilipRomano.jpg?width=160",
 "Willem Dafoe": "https://commons.wikimedia.org/wiki/Special:FilePath/Willem_Dafoe_Cannes_2019.jpg?width=160",
 "Ryan Reynolds": "https://commons.wikimedia.org/wiki/Special:FilePath/Deadpool_2_Japan_Premiere_Red_Carpet_Ryan_Reynolds_(cropped).jpg?width=160",
 "Morena Baccarin": "https://commons.wikimedia.org/wiki/Special:FilePath/Morena_Baccarin_at_the_2024_Toronto_International_Film_Festival_2_(cropped).jpg?width=160",
 "Ed Skrein": "https://commons.wikimedia.org/wiki/Special:FilePath/Ed_Skrein_by_Gage_Skidmore.jpg?width=160",
 "Edward Norton": "https://commons.wikimedia.org/wiki/Special:FilePath/Ed_Norton_and_Shauna_Robertson_TIFF_2025_(cropped).jpg?width=160",
 "Liv Tyler": "https://commons.wikimedia.org/wiki/Special:FilePath/Liv_Tyler_(2016)_(cropped).jpg?width=160",
 "Tim Roth": "https://commons.wikimedia.org/wiki/Special:FilePath/Tim_Roth_cropped.jpg?width=160",
 "William Hurt": "https://commons.wikimedia.org/wiki/Special:FilePath/History_of_Violence_002_(7271227040).jpg?width=160",
 "Don Cheadle": "https://commons.wikimedia.org/wiki/Special:FilePath/DonCheadle-byPhilipRomano.jpg?width=160",
 "Mickey Rourke": "https://commons.wikimedia.org/wiki/Special:FilePath/Mickey_Rourke_10_December_2010_(cropped).jpeg?width=160",
 "Natalie Portman": "https://commons.wikimedia.org/wiki/Special:FilePath/NataliePortman.jpg?width=160",
 "Anthony Hopkins": "https://commons.wikimedia.org/wiki/Special:FilePath/Anthony_Hopkins_Red_Sea_Festival_2025_Portrait.jpg?width=160",
 "Hayley Atwell": "https://commons.wikimedia.org/wiki/Special:FilePath/HVFFLondon2017Cap-ALS-29_(35183142201)_Cropped.jpg?width=160",
 "Hugo Weaving": "https://commons.wikimedia.org/wiki/Special:FilePath/MJK_08925_Hugo_Weaving_(Berlinale_2018)_bw.jpg?width=160",
 "Tommy Lee Jones": "https://commons.wikimedia.org/wiki/Special:FilePath/Tommy_Lee_Jones_2017.jpg?width=160",
 "Guy Pearce": "https://commons.wikimedia.org/wiki/Special:FilePath/Guy_Pearce_at_the_83rd_Venice_FILM_festival-22-2.jpg?width=160",
 "Ben Kingsley": "https://commons.wikimedia.org/wiki/Special:FilePath/Ben_Kingsley_by_Gage_Skidmore.jpg?width=160",
 "Christopher Eccleston": "https://commons.wikimedia.org/wiki/Special:FilePath/Christopher_Eccleston_London.jpg?width=160",
 "James Spader": "https://commons.wikimedia.org/wiki/Special:FilePath/James_Spader_by_Gage_Skidmore.jpg?width=160",
 "Paul Rudd": "https://commons.wikimedia.org/wiki/Special:FilePath/Paul_Rudd_and_Kate_Mara_at_the_2024_Toronto_International_Film_Festival_8_(cropped).jpg?width=160",
 "Michael Douglas": "https://commons.wikimedia.org/wiki/Special:FilePath/59th_Karlovy_Vary_International_Film_Festival%2C_Michael_Douglas_07_(cropped).jpg?width=160",
 "Evangeline Lilly": "https://commons.wikimedia.org/wiki/Special:FilePath/Evangeline_Lilly_2014_Comic_Con_(cropped).jpg?width=160",
 "Corey Stoll": "https://commons.wikimedia.org/wiki/Special:FilePath/Corey_Stoll_by_Gage_Skidmore.jpg?width=160",
 "Zoe Saldaña": "https://commons.wikimedia.org/wiki/Special:FilePath/Zoe_Salda%C3%B1a_at_the_2024_Toronto_International_Film_Festival_(cropped).jpg?width=160",
 "Kurt Russell": "https://commons.wikimedia.org/wiki/Special:FilePath/Kurt_Russell_by_Gage_Skidmore_2.jpg?width=160",
 "Michael Keaton": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Keaton_(NYCC_2014).JPG?width=160",
 "Michelle Pfeiffer": "https://commons.wikimedia.org/wiki/Special:FilePath/Michelle_Pfeiffer_Ant-Man_%26_The_Wasp_premiere_(cropped).jpg?width=160",
 "Brie Larson": "https://commons.wikimedia.org/wiki/Special:FilePath/Captain_Marvel_trailer_at_the_National_Air_and_Space_Museum_4_(cropped).jpg?width=160",
 "Samuel L. Jackson": "https://commons.wikimedia.org/wiki/Special:FilePath/SamuelLJackson.jpg?width=160",
 "Jude Law": "https://commons.wikimedia.org/wiki/Special:FilePath/Jude_Law_-_Headshot.jpg?width=160",
 "Ben Mendelsohn": "https://commons.wikimedia.org/wiki/Special:FilePath/Ben_Mendelsohn_2012.jpg?width=160",
 "Jake Gyllenhaal": "https://commons.wikimedia.org/wiki/Special:FilePath/Jake_Gyllenhaal_2019_by_Glenn_Francis.jpg?width=160",
 "Florence Pugh": "https://commons.wikimedia.org/wiki/Special:FilePath/Florence_Pugh_at_the_2024_Toronto_International_Film_Festival_13_(cropped_2_%E2%80%93_color_adjusted).jpg?width=160",
 "David Harbour": "https://commons.wikimedia.org/wiki/Special:FilePath/David_Harbour_by_Gage_Skidmore_2.jpg?width=160",
 "Rachel Weisz": "https://commons.wikimedia.org/wiki/Special:FilePath/Rachel_Weisz_2018.jpg?width=160",
 "Simu Liu": "https://commons.wikimedia.org/wiki/Special:FilePath/Simu_Liu_by_Gage_Skidmore.jpg?width=160",
 "Awkwafina": "https://commons.wikimedia.org/wiki/Special:FilePath/Awkwafina_by_Gage_Skidmore.jpg?width=160",
 "Tony Leung": "https://commons.wikimedia.org/wiki/Special:FilePath/Tony_Leung_as_the_President_of_the_International_Competition_Jury_at_Opening_Ceremony_of_the_Tokyo_International_Film_Festival_2024_(54578353950).jpg?width=160",
 "Michelle Yeoh": "https://commons.wikimedia.org/wiki/Special:FilePath/Michelle_Yeoh-2268.jpg?width=160",
 "Gemma Chan": "https://commons.wikimedia.org/wiki/Special:FilePath/Gemma_Chan_at_the_2026_Berlin_International_Film_Festival-69949_(cropped).jpg?width=160",
 "Richard Madden": "https://commons.wikimedia.org/wiki/Special:FilePath/Richard_Madden_by_Gage_Skidmore_2.jpg?width=160",
 "Angelina Jolie": "https://commons.wikimedia.org/wiki/Special:FilePath/Angelina_Jolie-643531_(cropped).jpg?width=160",
 "Salma Hayek": "https://commons.wikimedia.org/wiki/Special:FilePath/MKr383631_Salma_Hayek_(Women_In_Motion%2C_Cannes_2025)_crop.jpg?width=160",
 "Elizabeth Olsen": "https://commons.wikimedia.org/wiki/Special:FilePath/Elizabeth_Olsen_-_Los_Angeles_Comic_Con_2025.jpg?width=160",
 "Xochitl Gomez": "https://commons.wikimedia.org/wiki/Special:FilePath/Xochitl_Gomez_-_2024_(cropped).jpg?width=160",
 "Benedict Wong": "https://commons.wikimedia.org/wiki/Special:FilePath/Benedict_Wong_(28352087500)_(cropped).jpg?width=160",
 "Christian Bale": "https://commons.wikimedia.org/wiki/Special:FilePath/Christian_Bale-7837.jpg?width=160",
 "Tessa Thompson": "https://commons.wikimedia.org/wiki/Special:FilePath/Tessa_Thompson_at_the_2025_Toronto_International_Film_Festival._03_(cropped).jpg?width=160",
 "Letitia Wright": "https://commons.wikimedia.org/wiki/Special:FilePath/Letitia_Wright_by_Gage_Skidmore.jpg?width=160",
 "Angela Bassett": "https://commons.wikimedia.org/wiki/Special:FilePath/Angela_Bassett_by_Gage_Skidmoe.jpg?width=160",
 "Tenoch Huerta": "https://commons.wikimedia.org/wiki/Special:FilePath/Tenoch_Huerta_2024.jpg?width=160",
 "Jonathan Majors": "https://commons.wikimedia.org/wiki/Special:FilePath/Jonathan_Majors_on_ColliderVideo%2C_September_2018.png?width=160",
 "Kathryn Newton": "https://commons.wikimedia.org/wiki/Special:FilePath/Kathryn_Newton_during_an_interview%2C_February_2023_(cropped).jpg?width=160",
 "Teyonah Parris": "https://commons.wikimedia.org/wiki/Special:FilePath/TeyonahParris-byPhilipRomano_(cropped).jpg?width=160",
 "Hugh Jackman": "https://commons.wikimedia.org/wiki/Special:FilePath/Hugh_Jackman_Is_This_Thing_On-68_(cropped).jpg?width=160",
 "Emma Corrin": "https://commons.wikimedia.org/wiki/Special:FilePath/Emma_Corrin_in_2024_by_Gage_Skidmore.jpg?width=160",
 "Matthew Macfadyen": "https://commons.wikimedia.org/wiki/Special:FilePath/Matthew_Macfadyen_2007.jpg?width=160",
 "Anthony Mackie": "https://commons.wikimedia.org/wiki/Special:FilePath/2025_Anthony_Mackie_(cropped).jpg?width=160",
 "Harrison Ford": "https://commons.wikimedia.org/wiki/Special:FilePath/Harrison_Ford_-_Televerse_2025-03.jpg?width=160",
 "Danny Ramirez": "https://commons.wikimedia.org/wiki/Special:FilePath/Guests_at_the_2026_Met_Gala_416_(cropped).jpg?width=160",
 "Tim Blake Nelson": "https://commons.wikimedia.org/wiki/Special:FilePath/Tim_Blake_Nelson_Leaves_of_Grass_Premiere.jpg?width=160",
 "Julia Louis-Dreyfus": "https://commons.wikimedia.org/wiki/Special:FilePath/Julia_Louis-Dreyfus_2019_(2).jpg?width=160",
 "Pedro Pascal": "https://commons.wikimedia.org/wiki/Special:FilePath/Pedro_Pascal_by_Gage_Skidmore.jpg?width=160",
 "Vanessa Kirby": "https://commons.wikimedia.org/wiki/Special:FilePath/Vanessa_Kirby_at_the_2024_Toronto_International_Film_Festival_08_(Cropped).jpg?width=160",
 "Joseph Quinn": "https://commons.wikimedia.org/wiki/Special:FilePath/Joseph_Quinn_en_2022.jpg?width=160",
 "Ebon Moss-Bachrach": "https://commons.wikimedia.org/wiki/Special:FilePath/Ebon_Moss-Bachrach_by_Gage_Skidmore.jpg?width=160",
 "Sadie Sink": "https://commons.wikimedia.org/wiki/Special:FilePath/Sadie_Sink_(43914734441).jpg?width=160",
 "Jon Bernthal": "https://commons.wikimedia.org/wiki/Special:FilePath/JonBernthal-byPhilipRomano2.jpg?width=160",
 "Shaun Toub": "https://commons.wikimedia.org/wiki/Special:FilePath/Shaun_Toub_2011_cropped.jpg?width=160",
 "Faran Tahir": "https://commons.wikimedia.org/wiki/Special:FilePath/FaranTahirByPhilKonstantin2.jpg?width=160",
 "Leslie Bibb": "https://commons.wikimedia.org/wiki/Special:FilePath/Leslie_Bibb_2011_Shankbone.JPG?width=160",
 "Clark Gregg": "https://commons.wikimedia.org/wiki/Special:FilePath/ClarkGreggTIFFSept2012.jpg?width=160",
 "Bill Smitrovich": "https://commons.wikimedia.org/wiki/Special:FilePath/Bill_Smitrovich_thumbs_up_at_Schriever_AFB.jpg?width=160",
 "Paul Bettany": "https://commons.wikimedia.org/wiki/Special:FilePath/Paul_Bettany_-_Los_Angeles_Comic_Con_2025.jpg?width=160",
 "Jon Favreau": "https://commons.wikimedia.org/wiki/Special:FilePath/Jon_Favreau_2016.jpeg?width=160",
 "Jillian Morgese": "https://commons.wikimedia.org/wiki/Special:FilePath/Much_Ado_About_Nothing_Jillian_Morgese.jpg?width=160",
 "Jeremy Renner": "https://commons.wikimedia.org/wiki/Special:FilePath/Jeremy_Renner_at_TIFF_2025_(cropped).jpg?width=160",
 "Cobie Smulders": "https://commons.wikimedia.org/wiki/Special:FilePath/Cobie_Smulders_by_Gage_Skidmore_2.jpg?width=160",
 "Stellan Skarsgård": "https://commons.wikimedia.org/wiki/Special:FilePath/Stellan_Skarsg%C3%A5rd_at_the_2017_Berlinalevds.jpg?width=160",
 "Michael Rooker": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Rooker_2013_02_(cropped).jpg?width=160",
 "Lee Pace": "https://commons.wikimedia.org/wiki/Special:FilePath/Lee_Pace_Paris_Fashion_Week_Spring_Summer_2020.jpg?width=160",
 "Karen Gillan": "https://commons.wikimedia.org/wiki/Special:FilePath/Karen_Gillan_(53197567618).jpg?width=160",
 "Djimon Hounsou": "https://commons.wikimedia.org/wiki/Special:FilePath/Djimon_Hounsou_push_premiere_(cropped).jpg?width=160",
 "Glenn Close": "https://commons.wikimedia.org/wiki/Special:FilePath/Glenn_Close_2012_1.jpg?width=160",
 "Benicio del Toro": "https://commons.wikimedia.org/wiki/Special:FilePath/Benicio_Del_Toro_-_Guardians_of_the_Galaxy_premiere_-_July_2014_(cropped).jpg?width=160",
 "John C. Reilly": "https://commons.wikimedia.org/wiki/Special:FilePath/JohnCReillyJune09.jpg?width=160",
 "Frank Grillo": "https://commons.wikimedia.org/wiki/Special:FilePath/Frank_Grillo_by_Gage_Skidmore_2.jpg?width=160",
 "Georges St-Pierre": "https://commons.wikimedia.org/wiki/Special:FilePath/Georges_St-Pierre_crop.jpg?width=160",
 "Aaron Taylor-Johnson": "https://commons.wikimedia.org/wiki/Special:FilePath/Rahm_Emanuel%2C_Aaron_Taylor-Johnson_and_Brad_Pitt_at_'Bullet_Train'_event_at_Tokyo_Station_2022-08-23_cropped.jpg?width=160",
 "Alan Dale": "https://commons.wikimedia.org/wiki/Special:FilePath/Alan_DaleRev3.jpg?width=160",
 "Bernard White": "https://commons.wikimedia.org/wiki/Special:FilePath/Bernard_White_by_Gage_Skidmore.jpg?width=160",
 "Michael Stuhlbarg": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Stuhlbarg_at_Artios.jpg?width=160",
 "Mads Mikkelsen": "https://commons.wikimedia.org/wiki/Special:FilePath/Mads_Mikkelsen_Cannes_2013_2.jpg?width=160",
 "Amy Landecker": "https://commons.wikimedia.org/wiki/Special:FilePath/Amy_Landecker_at_the_2024_Toronto_International_Film_Festival_(cropped).jpg?width=160",
 "Scott Adkins": "https://commons.wikimedia.org/wiki/Special:FilePath/Scott_Adkins_(53319300983).jpg?width=160",
 "Benjamin Bratt": "https://commons.wikimedia.org/wiki/Special:FilePath/Benjamin_Bratt_at_the_2024_Toronto_International_Film_Festival_(cropped).jpg?width=160",
 "Jeff Goldblum": "https://commons.wikimedia.org/wiki/Special:FilePath/Jeff_Goldblum_by_Gage_Skidmore.jpg?width=160",
 "Karl Urban": "https://commons.wikimedia.org/wiki/Special:FilePath/Karl_Urban_by_Gage_Skidmore_3.jpg?width=160",
 "Idris Elba": "https://commons.wikimedia.org/wiki/Special:FilePath/Idris_Elba-4580_(cropped).jpg?width=160",
 "Sam Neill": "https://commons.wikimedia.org/wiki/Special:FilePath/Sir_Sam_Neill_2022.jpg?width=160",
 "Rachel House": "https://commons.wikimedia.org/wiki/Special:FilePath/Rachel_House_by_Gage_Skidmore.jpg?width=160",
 "Winston Duke": "https://commons.wikimedia.org/wiki/Special:FilePath/Winston_Duke_by_Gage_Skidmore.jpg?width=160",
 "Andy Serkis": "https://commons.wikimedia.org/wiki/Special:FilePath/Andy_Serkis_Comic-Con_2011.jpg?width=160",
 "Forest Whitaker": "https://commons.wikimedia.org/wiki/Special:FilePath/Forest_Whitaker_TIFF_2026_02_(cropped).jpg?width=160",
 "Florence Kasumba": "https://commons.wikimedia.org/wiki/Special:FilePath/Florence_Kasumba_at_The_Lion_King_European_Premiere_2019.png?width=160",
 "Daniel Kaluuya": "https://commons.wikimedia.org/wiki/Special:FilePath/Daniel_Kaluuya_by_Gage_Skidmore.jpg?width=160",
 "Sterling K. Brown": "https://commons.wikimedia.org/wiki/Special:FilePath/Sterling_K_Brown_-_Paradise.jpg?width=160",
 "Marisa Tomei": "https://commons.wikimedia.org/wiki/Special:FilePath/Marisa_Tomei_at_Berlinale_2023.jpg?width=160",
 "Jacob Batalon": "https://commons.wikimedia.org/wiki/Special:FilePath/Jacob_Batalon_(28035642754)_(cropped).jpg?width=160",
 "Tony Revolori": "https://commons.wikimedia.org/wiki/Special:FilePath/Tony_Revolori_by_Gage_Skidmore.jpg?width=160",
 "Alfred Molina": "https://commons.wikimedia.org/wiki/Special:FilePath/AlfredMolinaByJustinHoch2009.jpg?width=160",
 "Jamie Foxx": "https://commons.wikimedia.org/wiki/Special:FilePath/TIFF_2019_jamie_foxx_(cropped).jpg?width=160",
 "J. B. Smoove": "https://commons.wikimedia.org/wiki/Special:FilePath/JB_Smoove_2014_NBC_Universal_Summer_Press_Day_(cropped).jpg?width=160",
 "Angourie Rice": "https://commons.wikimedia.org/wiki/Special:FilePath/Angourie_Rice_-_Finding_Emily.jpg?width=160",
 "T. J. Miller": "https://commons.wikimedia.org/wiki/Special:FilePath/T._J._Miller_by_Gage_Skidmore.jpg?width=160",
 "Gina Carano": "https://commons.wikimedia.org/wiki/Special:FilePath/Gina_Carano_Photo_Op_GalaxyCon_Richmond_2024.jpg?width=160",
 "Brianna Hildebrand": "https://commons.wikimedia.org/wiki/Special:FilePath/Brianna_Hildebrand_by_Gage_Skidmore.jpg?width=160",
 "Leslie Uggams": "https://commons.wikimedia.org/wiki/Special:FilePath/Leslie_Uggams_1971.JPG?width=160",
 "Jed Rees": "https://commons.wikimedia.org/wiki/Special:FilePath/Jed_Rees_by_Gage_Skidmore.jpg?width=160",
 "Karan Soni": "https://commons.wikimedia.org/wiki/Special:FilePath/Karan_Soni_by_Gage_Skidmore.jpg?width=160",
 "Taylor Hickson": "https://commons.wikimedia.org/wiki/Special:FilePath/Taylor_Hickson_2019_(cropped).jpg?width=160",
 "Ty Burrell": "https://commons.wikimedia.org/wiki/Special:FilePath/Ty_Burrell_3_2014.jpg?width=160",
 "Peter Mensah": "https://commons.wikimedia.org/wiki/Special:FilePath/Peter_Mensah_Comic-Con_2009.jpg?width=160",
 "Lou Ferrigno": "https://commons.wikimedia.org/wiki/Special:FilePath/Lou_Ferrigno_during_Ribbon_Cutting_at_Galaxy_Con_Richmond_(cropped).jpg?width=160",
 "Stan Lee": "https://commons.wikimedia.org/wiki/Special:FilePath/Stan_Lee_December_2016.jpg?width=160",
 "Débora Nascimento": "https://commons.wikimedia.org/wiki/Special:FilePath/D%C3%A9bora_Nascimento_at_the_83rd_Venice_International_Film_Festival_%22Hombre_al_agua%22_premiere.jpg?width=160",
 "Sam Rockwell": "https://commons.wikimedia.org/wiki/Special:FilePath/Sam_Rockwell_(51492)_(cropped).jpg?width=160",
 "John Slattery": "https://commons.wikimedia.org/wiki/Special:FilePath/JohnSlattery08.jpg?width=160",
 "Garry Shandling": "https://commons.wikimedia.org/wiki/Special:FilePath/GarryShandlingApr2011.jpg?width=160",
 "Kate Mara": "https://commons.wikimedia.org/wiki/Special:FilePath/Kate_Mara_in_2024.jpg?width=160",
 "Kat Dennings": "https://commons.wikimedia.org/wiki/Special:FilePath/Kat_Dennings_-_The_40-Year-Old-Virgin.jpg?width=160",
 "Colm Feore": "https://commons.wikimedia.org/wiki/Special:FilePath/Colm_Feore_at_the_2013_Canadian_Film_Centre_Annual_Gala_%26_Auction.jpg?width=160",
 "Ray Stevenson": "https://commons.wikimedia.org/wiki/Special:FilePath/Ray_Stevenson_March_18%2C_2014_(cropped).jpg?width=160",
 "Rene Russo": "https://commons.wikimedia.org/wiki/Special:FilePath/Rene_Russo_1996.jpg?width=160",
 "Jaimie Alexander": "https://commons.wikimedia.org/wiki/Special:FilePath/Jaimie_Alexander%2C_London%2C_2013_(tone).jpg?width=160",
 "Stanley Tucci": "https://commons.wikimedia.org/wiki/Special:FilePath/ConclaveBFILFF101024_(9_of_44)_(54062519935)_(cropped).jpg?width=160",
 "Dominic Cooper": "https://commons.wikimedia.org/wiki/Special:FilePath/Dominic_Cooper_by_Gage_Skidmore.jpg?width=160",
 "Neal McDonough": "https://commons.wikimedia.org/wiki/Special:FilePath/Neal_McDonough_-_LACC_2021.jpg?width=160",
 "Derek Luke": "https://commons.wikimedia.org/wiki/Special:FilePath/NABJ_2013_-_Orlando_(9451924600).jpg?width=160",
 "Toby Jones": "https://commons.wikimedia.org/wiki/Special:FilePath/Toby_Jones_-_EmpireOfLightBFI121022_(30_of_33)_(52448062684).jpg?width=160",
 "Richard Armitage": "https://commons.wikimedia.org/wiki/Special:FilePath/Richard_Armitage_2014_(cropped).jpg?width=160",
 "Rebecca Hall": "https://commons.wikimedia.org/wiki/Special:FilePath/Rebecca_Hall_(2024)_(cropped).jpg?width=160",
 "James Badge Dale": "https://commons.wikimedia.org/wiki/Special:FilePath/James_Badge_Dale.jpg?width=160",
 "Stephanie Szostak": "https://commons.wikimedia.org/wiki/Special:FilePath/Stephanie_Szostak_2014.jpg?width=160",
 "William Sadler": "https://commons.wikimedia.org/wiki/Special:FilePath/William_Sadler_(cropped).jpg?width=160",
 "Dale Dickey": "https://commons.wikimedia.org/wiki/Special:FilePath/Dale_Dickey_(2018_crop).jpg?width=160",
 "Adewale Akinnuoye-Agbaje": "https://commons.wikimedia.org/wiki/Special:FilePath/Adewale_Akinnuoye-Agbaje_Thor_2_cropped.png?width=160",
 "Zachary Levi": "https://commons.wikimedia.org/wiki/Special:FilePath/Zachary_Levi_Comic-Con_2012.jpg?width=160",
 "Tadanobu Asano": "https://commons.wikimedia.org/wiki/Special:FilePath/Tadanobu_Asano_2011_(cropped).jpg?width=160",
 "Bobby Cannavale": "https://commons.wikimedia.org/wiki/Special:FilePath/Bobby_Cannavale_at_the_2024_Toronto_International_Film_Festival_(cropped).jpg?width=160",
 "Michael Peña": "https://commons.wikimedia.org/wiki/Special:FilePath/Actor_Michael_Pena.jpg?width=160",
 "Judy Greer": "https://commons.wikimedia.org/wiki/Special:FilePath/Judy_Greer_(46810958364)_(cropped).jpg?width=160",
 "T.I.": "https://commons.wikimedia.org/wiki/Special:FilePath/T.I._2022_Interview.png?width=160",
 "David Dastmalchian": "https://commons.wikimedia.org/wiki/Special:FilePath/David_Dastmalchian_-_Creep_I.E._Con_2026.jpg?width=160",
 "Wood Harris": "https://commons.wikimedia.org/wiki/Special:FilePath/Wood_harris_air_force1.jpg?width=160",
 "Abby Ryder Fortson": "https://commons.wikimedia.org/wiki/Special:FilePath/AbbyRyderFortson.jpg?width=160",
 "Emily VanCamp": "https://commons.wikimedia.org/wiki/Special:FilePath/Emily_VanCamp_at_Televerse_2026.jpg?width=160",
 "Sean Gunn": "https://commons.wikimedia.org/wiki/Special:FilePath/Sean_Gunn_January_2015.jpg?width=160",
 "Pom Klementieff": "https://commons.wikimedia.org/wiki/Special:FilePath/Stuttgart_-Comic_Con_Germany_2019-_7d_by-RaBoe_037_(cropped).jpg?width=160",
 "Steve Agee": "https://commons.wikimedia.org/wiki/Special:FilePath/Steve_Agee_by_Gage_Skidmore_3.jpg?width=160",
 "Elizabeth Debicki": "https://commons.wikimedia.org/wiki/Special:FilePath/Elizabeth_Debicki_by_Gage_Skidmore.jpg?width=160",
 "Chris Sullivan": "https://commons.wikimedia.org/wiki/Special:FilePath/Chris_Sullivan.jpg?width=160",
 "Tommy Flanagan": "https://commons.wikimedia.org/wiki/Special:FilePath/Tommy_Flanagan_by_Gage_Skidmore.jpg?width=160",
 "Laura Harrier": "https://commons.wikimedia.org/wiki/Special:FilePath/Laura_Harrier_Cannes_2018_2.jpg?width=160",
 "Donald Glover": "https://commons.wikimedia.org/wiki/Special:FilePath/Donald_Glover_TIFF_2015.jpg?width=160",
 "Martin Starr": "https://commons.wikimedia.org/wiki/Special:FilePath/Martin_Starr_by_Gage_Skidmore.jpg?width=160",
 "Abraham Attah": "https://commons.wikimedia.org/wiki/Special:FilePath/Abraham_Attah_(cropped).jpg?width=160",
 "Selenis Leyva": "https://commons.wikimedia.org/wiki/Special:FilePath/Selenis_Leyva.jpg?width=160",
 "Logan Marshall-Green": "https://commons.wikimedia.org/wiki/Special:FilePath/LoganMarshallGreen-byPhilipRomano.jpg?width=160",
 "Laurence Fishburne": "https://commons.wikimedia.org/wiki/Special:FilePath/Laurence_Fishburne_at_53rd_Saturn_Awards_2026.jpg?width=160",
 "Hannah John-Kamen": "https://commons.wikimedia.org/wiki/Special:FilePath/Hannah_John-Kamen_MTV_International_2018_(cropped).jpg?width=160",
 "Randall Park": "https://commons.wikimedia.org/wiki/Special:FilePath/Randall_Park_-_Girl_Group_-_TIFF_2026.jpg?width=160",
 "Walton Goggins": "https://commons.wikimedia.org/wiki/Special:FilePath/Walton_Goggins.jpg?width=160",
 "Mckenna Grace": "https://commons.wikimedia.org/wiki/Special:FilePath/McKenna_Grace_at_WWD_Style_Awards_2026.jpg?width=160",
 "Lashana Lynch": "https://commons.wikimedia.org/wiki/Special:FilePath/Captain_Marvel_at_Edwards_Air_Force_Base_06_(cropped).png?width=160",
 "Algenis Perez Soto": "https://commons.wikimedia.org/wiki/Special:FilePath/Algenis_Perez_Soto_en_LosCriticologos.jpg?width=160",
 "Rune Temte": "https://commons.wikimedia.org/wiki/Special:FilePath/Rune_Temte.jpg?width=160",
 "Remy Hii": "https://commons.wikimedia.org/wiki/Special:FilePath/Remy_Hll_(39829198722).jpg?width=160",
 "O. T. Fagbenle": "https://commons.wikimedia.org/wiki/Special:FilePath/O._T._Fagbenle_by_Gage_Skidmore.jpg?width=160",
 "Ray Winstone": "https://commons.wikimedia.org/wiki/Special:FilePath/Ray_Winstone_2014.jpg?width=160",
 "Olga Kurylenko": "https://commons.wikimedia.org/wiki/Special:FilePath/Festival_de_Cinema_de_Sitges_2019_(49500414408)_(cropped).jpg?width=160",
 "Fala Chen": "https://commons.wikimedia.org/wiki/Special:FilePath/FalaChenJune2024.png?width=160",
 "Florian Munteanu": "https://commons.wikimedia.org/wiki/Special:FilePath/Florian_Munteanu_-_IGN_Live_2024.jpg?width=160",
 "Ronny Chieng": "https://commons.wikimedia.org/wiki/Special:FilePath/Ronny_Chieng_2018.png?width=160",
 "Dallas Liu": "https://commons.wikimedia.org/wiki/Special:FilePath/Dallas_Liu_GalaxyCon_Raleigh_2024.jpg?width=160",
 "Yuen Wah": "https://commons.wikimedia.org/wiki/Special:FilePath/Yuen_Wah_(2024).jpg?width=160",
 "Jodi Long": "https://commons.wikimedia.org/wiki/Special:FilePath/Actress_Jodi_Long_in_1000_Airplanes_on_the_Roof_(1988)_(cropped).jpg?width=160",
 "Kumail Nanjiani": "https://commons.wikimedia.org/wiki/Special:FilePath/KumailAliNanjiani.jpg?width=160",
 "Lauren Ridloff": "https://commons.wikimedia.org/wiki/Special:FilePath/Lauren_Ridloff_2018-05-27.jpg?width=160",
 "Brian Tyree Henry": "https://commons.wikimedia.org/wiki/Special:FilePath/Brian_Tyree_Henry_by_Gage_Skidmore.jpg?width=160",
 "Ma Dong-seok": "https://commons.wikimedia.org/wiki/Special:FilePath/Don_Lee_by_Gage_Skidmore.jpg?width=160",
 "Lia McHugh": "https://commons.wikimedia.org/wiki/Special:FilePath/Lia_McHugh_by_Gage_Skidmore.jpg?width=160",
 "Barry Keoghan": "https://commons.wikimedia.org/wiki/Special:FilePath/Barry_Keoghan_2024_(cropped).jpg?width=160",
 "Kit Harington": "https://commons.wikimedia.org/wiki/Special:FilePath/Kit_harrington_by_sachyn_mital_(cropped_2).jpg?width=160",
 "Haaz Sleiman": "https://commons.wikimedia.org/wiki/Special:FilePath/Haaz_Sleiman_2008_cropped.jpg?width=160",
 "Patrick Stewart": "https://commons.wikimedia.org/wiki/Special:FilePath/Patrick_Stewart_by_Gage_Skidmore_2.jpg?width=160",
 "Anson Mount": "https://commons.wikimedia.org/wiki/Special:FilePath/Anson_Mount_by_Gage_Skidmore.jpg?width=160",
 "John Krasinski": "https://commons.wikimedia.org/wiki/Special:FilePath/John_Krasinski_and_Josh_Wood_(cropped).jpg?width=160",
 "Taika Waititi": "https://commons.wikimedia.org/wiki/Special:FilePath/Taika_Waititi_photo_by_pouria_afkhami_(cropped).jpg?width=160",
 "Matt Damon": "https://commons.wikimedia.org/wiki/Special:FilePath/MattDamon-byPhilipRomano2.jpg?width=160",
 "Luke Hemsworth": "https://commons.wikimedia.org/wiki/Special:FilePath/Luke_Hemsworth_by_Gage_Skidmore.jpg?width=160",
 "Russell Crowe": "https://commons.wikimedia.org/wiki/Special:FilePath/Russell_Crowe_on_the_Green_Carpet_at_the_2025_Zurich_Film_Festival_06_(cropped).jpg?width=160",
 "Dominique Thorne": "https://commons.wikimedia.org/wiki/Special:FilePath/DominiqueThorn-byPhilipRomano.jpg?width=160",
 "Martin Freeman": "https://commons.wikimedia.org/wiki/Special:FilePath/Martin_Freeman-5341.jpg?width=160",
 "Michaela Coel": "https://commons.wikimedia.org/wiki/Special:FilePath/Michaela_Coel_Peabody_Awards%2C_June_2021.png?width=160",
 "Bill Murray": "https://commons.wikimedia.org/wiki/Special:FilePath/Bill_Murray-8882.jpg?width=160",
 "Gregg Turkington": "https://commons.wikimedia.org/wiki/Special:FilePath/Neil_Hamburger.jpg?width=160",
 "William Jackson Harper": "https://commons.wikimedia.org/wiki/Special:FilePath/William_Jackson_Harper_at_the_2018_Comic-Con_International_(42913092745)_(cropped).jpg?width=160",
 "Will Poulter": "https://commons.wikimedia.org/wiki/Special:FilePath/Will_Poulter_Sundance_2026.jpg?width=160",
 "Sylvester Stallone": "https://commons.wikimedia.org/wiki/Special:FilePath/Sylvester_Stallone_Cannes_2019.jpg?width=160",
 "Chuk Iwuji": "https://commons.wikimedia.org/wiki/Special:FilePath/Chukwudi_Iwuji_2022.jpg?width=160",
 "Michael Rosenbaum": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Rosenbaum_Photo_Op_GalaxyCon_Richmond_2020.jpg?width=160",
 "Zawe Ashton": "https://commons.wikimedia.org/wiki/Special:FilePath/Zawe_Ashton_2013.jpg?width=160",
 "Park Seo-joon": "https://commons.wikimedia.org/wiki/Special:FilePath/Park_Seo-joon_in_June_2019.png?width=160",
 "Zenobia Shroff": "https://commons.wikimedia.org/wiki/Special:FilePath/Shroff_Sacred_Heart_University_Film_TV_Master_Program_November_2018.jpg?width=160",
 "Mohan Kapur": "https://commons.wikimedia.org/wiki/Special:FilePath/Mohan_Kapoor.jpg?width=160",
 "Jennifer Garner": "https://commons.wikimedia.org/wiki/Special:FilePath/Jennifer_Garner_at_the_Fast_Company_Innovation_Festival_-_44972951114_(cropped).jpg?width=160",
 "Rob Delaney": "https://commons.wikimedia.org/wiki/Special:FilePath/Rob_Delaney.jpg?width=160",
 "Stefan Kapičić": "https://commons.wikimedia.org/wiki/Special:FilePath/2.9.16StefanKapi%C4%8Di%C4%87ByLuigiNovi8b.jpg?width=160",
 "Shira Haas": "https://commons.wikimedia.org/wiki/Special:FilePath/Shira_Haas_01.webp?width=160",
 "Carl Lumbly": "https://commons.wikimedia.org/wiki/Special:FilePath/Carl_Lumbly%2C_South_High_School_yearbook%2C_1969.png?width=160",
 "Giancarlo Esposito": "https://commons.wikimedia.org/wiki/Special:FilePath/Giancarlo_Esposito_Anemone-22_(cropped).jpg?width=160",
 "Xosha Roquemore": "https://commons.wikimedia.org/wiki/Special:FilePath/Xosha_Roquemore_on_RealTVfilms.jpg?width=160",
 "Wyatt Russell": "https://commons.wikimedia.org/wiki/Special:FilePath/Wyatt_Russell_on_Wizard_Radio_Media.jpg?width=160",
 "Lewis Pullman": "https://commons.wikimedia.org/wiki/Special:FilePath/Lewis_Pullman_at_San_Diego_Comic_Con_2026-2.jpg?width=160",
 "Geraldine Viswanathan": "https://commons.wikimedia.org/wiki/Special:FilePath/Geraldine_Viswanathan_at_SXSW_Red_Carpet_premiere_of_BLOCKERS_adjusted_(cropped).jpg?width=160",
 "Chris Bauer": "https://commons.wikimedia.org/wiki/Special:FilePath/ChrisBauerSDComicConJuly2014.jpg?width=160",
 "Wendell Pierce": "https://commons.wikimedia.org/wiki/Special:FilePath/WendellPierce.jpg?width=160",
 "Ralph Ineson": "https://commons.wikimedia.org/wiki/Special:FilePath/Ralphinesonadjusted.jpg?width=160",
 "Julia Garner": "https://commons.wikimedia.org/wiki/Special:FilePath/Julia_Garner_Berlinale_2020_(cropped)_2.jpg?width=160",
 "Paul Walter Hauser": "https://commons.wikimedia.org/wiki/Special:FilePath/Paul_Walter_Hauser.jpg?width=160",
 "John Malkovich": "https://commons.wikimedia.org/wiki/Special:FilePath/John_Malkovich%2C_Berlinale_2023_cropped.jpg?width=160",
 "Natasha Lyonne": "https://commons.wikimedia.org/wiki/Special:FilePath/Natasha_Lyonne_-_Dascha_Polanco_(14471678018)_(Lyonne_cropped).jpg?width=160",
 "Mark Gatiss": "https://commons.wikimedia.org/wiki/Special:FilePath/Mark_Gatiss_at_A_Scandal_in_Belgravia_screening.png?width=160",
 "Michael Mando": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Mando_by_Gage_Skidmore.jpg?width=160",
 "Tramell Tillman": "https://commons.wikimedia.org/wiki/Special:FilePath/TramellTillman.jpg?width=160",
 "Krondon": "https://commons.wikimedia.org/wiki/Special:FilePath/Marvin_%22Krondon%22_Jones_III_(47086136322).jpg?width=160",
 "Eman Esfandi": "https://commons.wikimedia.org/wiki/Special:FilePath/Eman_Esfandi_GalaxyCon_San_Jose_August-29-2026_586.jpg?width=160",
 "Zabryna Guevara": "https://commons.wikimedia.org/wiki/Special:FilePath/Zabryna_Guevara_at_NY_PaleyFest_2014_for_Gotham.jpg?width=160"
};
